### ISSUE TITLE
Feature Request: visualizing separations or groups or delineations of tiles

### ISSUE THREAD

**Issue by michael-smith-qs2** [neo4j-labs/neodash#101]
Users may want to group tiles together visually, to convey a message or that a dashboard has moved onto a different section or idea. Maybe a simple way of doing this would be adding in a vertical or horizontal line? But drawing a box around tiles or background tinting, maybe with color options, could work too?

**Comment by BennuFire** [comment]
Hi!

This can be done with background colors.
