### ISSUE TITLE
Feature Request: button to 'duplicate' or 'copy' tile

### ISSUE THREAD

**Issue by michael-smith-qs2** [neo4j-labs/neodash#103]
When creating tiles, users may want the ability to duplicate or copy an existing tile into a new one, as there may be only tweaks or changes, instead of starting from scratch.

**Comment by Raj725** [comment]
It will be useful. Sometimes, we even need to copy the page and make small changes. Currently, I'm saving the dashboard to a JSON file, duplicating the page, and reloading.
