### ISSUE TITLE
Feature Request: "tag" and "latest" functionality on generated links for sharing

### ISSUE THREAD

**Issue by michael-smith-qs2** [neo4j-labs/neodash#108]
As-is, with sharing updates to existing dashboards, we require to save to neo4j and generate a new link to share with users or clients. This contains what looks like a new UUID even for minor tweaks. Two ideas along these lines to improve this:
- Would it be possible to have link-sharing get some sort of "latest" functionality" that could always point to the newest node? This "newest" idea could either be overall, or by tag (below). This would obviate the need to generate new links for sharing every time we make an update.
- Would it be possible to have link-sharing get an optional "tag" (e.g., "Dashboard for Client A")? This would allow categorization of dashboards when saving, and might play well with the "latest" idea too.

**Comment by alfredorubin96** [comment]
@nielsdejong now that we have labels on dashboards, is this still relevant?

**Comment by alfredorubin96** [comment]
I'll close this issue because we can now add labels to dashboards. Feel free to reopen it if needed.
