### ISSUE TITLE
[Feature Improvement] Graph: No overlapping lines

### ISSUE THREAD

**Issue by JoridK** [neo4j-labs/neodash#109]
Hi again,

Would it be possible to prevent lines in a graph from crossing anywhere except in shared nodes?
(Using force-directed layout atm)
In the right graph, you can see that NeoDash orders the points so that it looks a bit like there is a circle, but there is none. The left picture is the same graph reordered.
![2022_03_15_10_51_04_NeoDash_Neo4j_Dashboard_Builder](https://user-images.githubusercontent.com/99267906/158352118-f8b41a7e-64a5-4212-b82c-b32d7ea942b6.png)

**Comment by alfredorubin96** [comment]
HI @JoridK, i'll close this issue because i think you can solve this by changing the graph layout. Feel free to reopen it if needed.
