### ISSUE TITLE
[Feature Request] Find nodes in graph or map by attribute

### ISSUE THREAD

**Issue by JoridK** [neo4j-labs/neodash#111]
Hi again,

would it be possible to search the graph / map by certain attributes, and then highlight all nodes that fulfill the search parameter? 
This would be very handy in large graphs (and maps), for example if I want to find a node by its attribute "movie title" and I only want the "Matrix" series, but I have 200 other movies in there. Currently it takes a long time to find them, and it is very easy to loose them again.

**Comment by alfredorubin96** [comment]
Hi @JoridK , i think Bloom is a Neo4j Bloom is more useful in terms of graph exploration, so you could embed that inside neodash using an Iframe or you can use parameter selectors to highlight the nodes inside the graph visualization using Rule Based Styling.
