### ISSUE TITLE
[Feature Request] Multi-database management

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#118]
I allow myself to put the idea here in case other people have remarks.

1. Right now, `NeoDash` use the same database for the whole dashboard. So the idea would be to have a default database but to be able to change the database for each report.

2. Another feature linked to the previous one would be able to merge results from several databases. For example, in the `Line chart` report, each line could represent a line of data from different databases. An idea to achieve that would be to allow users to create `NeoDash` variables that could be used in other reports.

Thank you!
Cobra

**Comment by DrobConsulting** [comment]
even just the ability of being able to change the database per tile would be very useful

**Comment by BennuFire** [comment]
Hi @Cobra5197  

The future is here. We just released 2.1.8 that includes the database selection per tile. About 2. Can you create a different issue better explaining you idea? You can always try yourself and PR us 👯‍♂️

**Comment by MoshiAL** [comment]
I've tried using this new feature with a neo4j 4.1.2 server and the dashboard selector doesn't work for me.
Is it a problem with the neo4j version?
