### ISSUE TITLE
Dockerfile problem

### ISSUE THREAD

**Issue by Kafkamorph** [neo4j-labs/neodash#121]
# docker-compose up -d
Building neodash
Sending build context to Docker daemon  4.964MB
Error response from daemon: Dockerfile parse error line 44: ARG requires exactly one argument
ERROR: Service 'neodash' failed to build : Build failed

**Comment by nielsdejong** [comment]
hi @Kafkamorph ,
Thanks for reaching out. Are you running NeoDash from a Windows system? I have seen problems in the past where Windows had trouble working with the Dockerfile. You could also try commenting out line 44 and see if that fixes it.

Let me know if you manage to make it work,
Niels
