### ISSUE TITLE
NeoDash with KeyCloak Documenation

### ISSUE THREAD

**Issue by DrobConsulting** [neo4j-labs/neodash#133]
I have keycloak set up with Neo4j using the neo4j.conf file. I'm confused by the documentation on how to set up SSO with neodash.  Specifically what does this block expect:

location /auth_provider {
        default_type application/json;
        return 200 '{
                        "auth_config" : {
                            "oidc_providers" : [ ... ]
                        }
                    }';
    }

Would it be possible to include an example of how this block should be set up with either Keycloak or Okta.

**Comment by tinquen12** [comment]
Hello,
In fact you have nothing to do on the keycloak side. As soon as you have a neo4j database with an sso provider setup. 

The only thing to do is to provide `ssoDiscoveryUrl` to `http://localhost:7687/auth_provider`. I assume in that example that your neo4j database is hosted on localhost on port 7687

I hope this is useful. 😄

**Comment by BennuFire** [comment]
Hi @DrobConsulting ,

I saw another issue related to the SSO connection so I guess you were able to configure it.
