### ISSUE TITLE
Hierarchical Graph view similar to Bloom

### ISSUE THREAD

**Issue by rgb-panda** [neo4j-labs/neodash#142]
Hello,

Are there any plans to support Hierarchical views on graphs similar to how Bloom does it? I tried force-directed but it's not the same. Below is an example from Neodash, and Bloom 

Thanks!

![image](https://user-images.githubusercontent.com/1173031/169658817-c80ec300-671f-4718-b6bc-5317ba002ef8.png)
![image](https://user-images.githubusercontent.com/1173031/169658821-0359ad7a-b852-452c-a37f-e14ed4aa5636.png)

**Comment by rgb-panda** [comment]
react-force-graph does seem to support it with td = tree option

https://vasturiano.github.io/react-force-graph/example/tree/
https://github.com/vasturiano/react-force-graph/blob/master/example/tree/index.html

but when I tried tree with neodash I got a weird result like below

![image](https://user-images.githubusercontent.com/1173031/169661378-f17f063a-2ec3-4077-a65e-12d7cc9d1e2f.png)

**Comment by emigre459** [comment]
+1 to this. I tried to use the tree layout in the Advanced options for graph tiles but it seems to just be pushing out force-directed layout unfortunately.

**Comment by alfredorubin96** [comment]
Hi @rgb-panda, thank you for creating this issue. I'll close this issue because there are different layout options inside Neodash, feel free to reopen it if needed.
