### ISSUE TITLE
Docker volume config to persist state

### ISSUE THREAD

**Issue by mpharding** [neo4j-labs/neodash#149]
Hi,

Which directories require a volume mapping if I want to re-establish the state after rebuilding the container?

Thanks,
Mike

**Comment by BennuFire** [comment]
Hi @mpharding !

Technically non. I guess you are talking about your Dashboard state. This is something that gets saved on your client Session Storage. Or were you talking about something else?

Sorry for our late responses :(

**Comment by jan4984** [comment]
@mpharding dashboards are saved in neo4j. https://github.com/neo4j-labs/neodash/blob/master/src/dashboard/DashboardThunks.ts#L154
