### ISSUE TITLE
Display value of Node property as Node label

### ISSUE THREAD

**Issue by dpeachey** [neo4j-labs/neodash#153]
Hi,

Is it possible in the table view to display the value of a property of the Node as the label for the node?

For example, in the following table:

<img width="593" alt="Screenshot 2022-06-02 at 15 52 57" src="https://user-images.githubusercontent.com/78757348/171645284-0d0d5fa1-813b-4a73-83e1-2aab120dc2a5.png">

...I would like to display the FlowNode.name value as the label for the node instead of FlowNode.

Does anyone know if this is possible? Or is there another way I can achieve a similar output?

Thanks,

Dan

**Comment by BennuFire** [comment]
Hi @dpeachey ,

Related to this. We will not implement a native way to do this translation. However, you can adapt your queries in order o achieve this with the usage of virtual node/relationships. https://neo4j.com/labs/apoc/4.2/overview/apoc.create/apoc.create.vNode/

Hopefully this will be useful enough.
