### ISSUE TITLE
When sharing dashboards from a custom deplyoment use URL instead of "neodash.graphapp.io" 

### ISSUE THREAD

**Issue by nukerxy** [neo4j-labs/neodash#159]
Hi 
## Feature request

**Is your feature request related to a problem? Please describe.**
When connected to a self-hosted instance (Editor Mode) and using the dashboard share function, the generated link will be something like
http://neodash.graphapp.io/?share&type=[...]

**Describe the solution you'd like**
I would like the link to refer to the current URL NeoDash is running on.

Example: 
NeoDash can be reached under 
http://custom-neodash.company.com/

Generated link should be
http://custom-neodash.company.com/?share&type=[...]

**Describe alternatives you've considered**
Doing the replacement "by hand"

**Comment by BennuFire** [comment]
Hi,

Thanks for your suggestion. This will be part of the next release. 😁
