### ISSUE TITLE
Line chart not plotting

### ISSUE THREAD

**Issue by username-rp** [neo4j-labs/neodash#165]
Hello,

Firstly - this is a great product. Thank you for creating it.

I am trying to plot a line chart; the query returns the following data in table format:
![image](https://user-images.githubusercontent.com/68271223/179555863-d243a96d-d245-4225-b29f-1e49f7d7c526.png)

The line chart fails to plot. The data types are datetimes and integers. Does the line chart time series require equally spaced data?

Thanks!

**Comment by nielsdejong** [comment]
hi @username-rp ,
This issue has been fixed in a recent release, when we added support for date objects (in addition to the existing datetime objects). Thanks for reporting this and let us know if you experience any more issues.

Niels

**Comment by nielsdejong** [comment]
hi @username-rp ,
This issue has been fixed in a recent release, when we added support for date objects (in addition to the existing datetime objects). Thanks for reporting this and let us know if you experience any more issues.

Niels
