### ISSUE TITLE
[Feature Request] Refresh button

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#166]
Hello,

I would love to have a refresh button next to the maximize and settings buttons. The aim is to have the possibility to manually refresh the visualization when needed and not to wait for x seconds.

Cobra

**Comment by mariusconjeaud** [comment]
See pull request #277.

Introducing a "lastRunTimestamp" prop tracking the last refresh trigger. This can be updated by : query change, click on save button (aka close settings), change a relevant parameter, click on Refresh button.
