### ISSUE TITLE
Map View Crashes when selecting node-label dropdown

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/neodash#183]
MATCH (s:Station) RETURN s LIMIT 10

Based on Jesus' Rail UK dataset
https://github.com/jbarrasa/gc-2022/tree/main/interop

Did my own import, set location as geocoordinate point and created index.

- only configured relWidthProperty and heatmap markers
- nothing else

MapChart.tsx:256 Uncaught ReferenceError: renderNodeLabel is not defined
    at MapChart.tsx:256:22
    at Array.map (<anonymous>)
    at MapChart.tsx:250:105
    at qA (MapChart.tsx:327:46)
    at ra (index.js:157:137)
    at Fa (index.js:180:154)
    at Bs (index.js:269:343)
    at wl (index.js:250:347)
    at El (index.js:250:278)
    at _l (index.js:250:138)

**Comment by nielsdejong** [comment]
Hi Michael, thanks for reporting this. I'll try and reproduce the issue locally and will push a fix a.s.a.p. CC @mariusconjeaud

**Comment by nielsdejong** [comment]
Issue is fixed here: https://github.com/neo4j-labs/neodash/pull/184

Update is pushed as part of the 2.1.4 release out today too.

Best,
Niels
