### ISSUE TITLE
Feature request: add pagenumber as a url_parameter

### ISSUE THREAD

**Issue by ksipma** [neo4j-labs/neodash#187]
I found out that it's possible to use the neodash_xxx parameters as a url parameter. Now I can create links to filter the data . However I cannot seem to change the page of the dashboard using parameters. This would be handy in my use case and perhaps also for others too.

**Comment by nielsdejong** [comment]
Hi @ksipma - this feature will be added as part of the 2.1.6 release:
https://github.com/neo4j-labs/neodash/pull/196
Thank you for your suggestion.

Niels

**Comment by nielsdejong** [comment]
Adding parameters in the URL is now available (version 2.1.6 and beyond).
Thanks for the suggestion!
