### ISSUE TITLE
Sankey Plot can crash dashboard

### ISSUE THREAD

**Issue by dschmitz89** [neo4j-labs/neodash#203]
## Guidelines

- NeoDash version: 2.1.5
- Neo4j Database version: 4.3 Community

- **Steps to reproduce**
When a circular link is detected in a sankey plot, the complete browser window crashes.
I could not narrow it down more as I am confused that there whould be circular links in the first place in the data I passed to it. Anyhow, whatever the user's query is, it should only crash the Sankey plot, not the complete dashboard. In case that the dashboard is reloaded from the cache, it also directly crashes again, making it impossible to save progress done elsewhere.

Could you please have a look for the next release?

CC @BennuFire 

![image](https://user-images.githubusercontent.com/40656107/189913409-3d863714-4709-431e-8327-489eb8df9fb0.png)

**Comment by nielsdejong** [comment]
Hi Daniel, this issue has been resolved in version 2.1.6.
Thanks for letting us know!

Niels
