### ISSUE TITLE
Clicking Help Button opens Documentation in Dashboard Windows with no way back

### ISSUE THREAD

**Issue by luzidl** [neo4j-labs/neodash#209]
## Help Button Issue

When opening a new report and clicking on the little (?)-button in the left upper part of the report (Step 1 below), this opens a new windows named "About Reports". 
Clicking on the "Documentation"-Link  (Step 2 below) in that window, the Neo4j Lab Documentation page is opened in the NeoDash Window where you were working on your Dashboard. There seems to be now way back to the dashboard anymore. The only way to get back to that dashboard is closing the NeoDash Window and re-open NeoDash. I would prefer a new window with the documentation, instead of using the current dashboard window to not loose any work.

Here is the way to reproduce it:
Step 1:
<img width="321" alt="step1" src="https://user-images.githubusercontent.com/8035021/193217946-f71618e5-fad4-4d20-b5d8-a542b8be3386.png">

Step 2:
<img width="1162" alt="step2" src="https://user-images.githubusercontent.com/8035021/193218129-04d61283-a8eb-4f9c-98be-ace685505472.png">

Step 3 (Docs page opens with now way back to your dashboard):
<img width="1762" alt="step3" src="https://user-images.githubusercontent.com/8035021/193218287-774ca33a-0b3a-4ffe-918c-b8debb1f342b.png">

**Comment by nielsdejong** [comment]
Hi @luzidl , thanks for reporting this!
We've resolved this issue in 2.1.6. Please keep us posted if you come across other issues.

Best,
Niels
