### ISSUE TITLE
Create and Delete Operations in Neodash

### ISSUE THREAD

**Issue by icimidemirag** [neo4j-labs/neodash#218]
Hi, create and delete operations can be performed in Neodash. Is this a bug? A dashboard application should not be able to modify the database. Is there any particular reason why you don't block the create and delete operations? If not, I suggest you disable these operations.

**Comment by BennuFire** [comment]
Hi @icimidemirag !

It's not a bug. We have plans on our roadmap to include ways to update/create/delete things if the user want it. If you  are concern about the integrity of your database instance, please consider creating a read-only user on it and use it when connecting to NeoDash.  

Thanks a lot!

**Comment by icimidemirag** [comment]
I want to make a user-interactive dashboard, so the user can run any match cypher they want.  How can I do that? 
 Maybe you can add a feature to block unwanted commands, so that I can customize the dashboard so that it doesn't run commands other than match?

**Comment by BennuFire** [comment]
Hi!

Are you running on community Edition or Enterprise? In the latter, you can create users with just READ privileges so the only type of queries that going to get executed are the MATCH ones.

https://neo4j.com/docs/cypher-manual/current/access-control/manage-users/
