### ISSUE TITLE
Report title on download

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#228]
It would be nice if the report title were included on top of the downloaded image. 
The image would then be ready for use e.g. in a text document without needing photoshopping to add the title.
Thank you.

**Comment by alfredorubin96** [comment]
Here an example of what you asked, is it fine? Is not that easy to remove the buttons from the image.
![image(10)](https://user-images.githubusercontent.com/103421036/204511831-9fefee11-84b0-4124-a24b-b52f18ec6b93.png)
Let us know if you have some feedbacks

**Comment by gcthys** [comment]
![image (2)](https://user-images.githubusercontent.com/68611501/204512683-eb0ecab2-dd82-40c3-972d-24cf61bc730f.png)

This is an example of what a download looks like now.
It would indeed be nice to have the title above.
I understand the system takes a "snapshot" of the report "as is" and that it is therefore not possible to remove the buttons and sliders from the top and bottom. This is not ideal, but it's better than having no title at all :-)
Thanks
