### ISSUE TITLE
Colour styling of reports

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#229]
Would it be made possible to determine the background colour of each individual report?
It would be very handy if e.g. different types of reports on the same tab could be distinguished from each other in this way.
The same mechanics as the rule-based styling would be perfect.
Thank you.

**Comment by BennuFire** [comment]
Hi @gcthys !

This can be added to every report that same way is already there for the Single Value, I'll will add that on the pipeline. In this case, it not a rule based style condition. How did you immagine this 2 working together?

![image](https://user-images.githubusercontent.com/7397411/200202496-567750ca-e74f-4542-b3bc-1d6a64c54c5e.png)


Thanks for using Neodash,

Harold

**Comment by gcthys** [comment]
@BennuFire 

Hello Harold,
thank you for picking this up!
My apologies for the clumsy formulation of my request: adding it to the Advanced Settings would be perfect. 
Attached is a raw impression of what I meant: the single value in the top left corner has been coloured with the Advanced Settings and the other two reports should be coloured in the same way.
Guido
![Afbeeldinvbnvbg1](https://user-images.githubusercontent.com/68611501/200260517-d744bb21-b5b8-40b7-a1de-57767f6bb099.png)

**Comment by BennuFire** [comment]
Hi @gcthys ,

I just added the background color options to our next release 2.2. By the moment you read this post, it should already be available for you to enjoy it.

Thanks for your valuable suggestion.

**Comment by gcthys** [comment]
@BennuFire 
Hi Harold,
I just checked and as far as I can see, the background colour option is now available on Single Value and Graph, nut not on the report types, is that correct?
Guido

**Comment by BennuFire** [comment]
Hi @gcthys!

Have you upgrade to 2.2.0?

Harold

**Comment by gcthys** [comment]
I am using console.neo4j.io + the browser version of NeoDash and that indicates it is still on V1.1.10-extended

**Comment by BennuFire** [comment]
Hi @gcthys! 


Can you try your dashboard on http://neodash.graphapp.io/?  Can you detail more on your setup? Weird!

**Comment by BennuFire** [comment]
Hi @gcthys,

We do save the operational state of the dashboard on a 'cookie' that can later be persisted on the database. There're a couple of concepts I need to better understand. We're do you see V1. 1.10-extended? We have never released that.  The dashboard I see about movies, is something persisted on your database? Is the gallery example?

In general, the upgrade happens on the cookie version of the dashboard that then you need to persist on a database of your own.

**Comment by gcthys** [comment]
The version is mentioned in the bottom right corner of the popup generated by the circled "i" in the left toolbar. In the background you can see my own dashboard:

![Schermafdruk 2022-11-11 10 53 54](https://user-images.githubusercontent.com/68611501/201315351-30dff8b2-e39f-4bd6-86da-4636ceeba99d.png)

The movie database is the sample I opened, as mentioned in my previous comment. That is where the upgrade went okay. The correct version is also mentioned on the i-popup.
But I never use that database and I think it is even first time ever that I opened it.

Can you send me the name of the cookie you are using? Because it doesn't start with "neo", see previous screen print.

**Comment by gcthys** [comment]
@BennuFire 
Additionally: I just noticed that V1. 1.10-extended is also mentioned in the debug report:

[neodash-debug-state.zip](https://github.com/neo4j-labs/neodash/files/9990453/neodash-debug-state.zip)

Hope this helps.

**Comment by BennuFire** [comment]
Hi @gcthys !

Just as a follow up. About the cookies, I do correct myself. We use localStorage (not exactly a cookie from the privacy point of view) that gets deleted whenever you delete cookies tho. 

![image](https://user-images.githubusercontent.com/7397411/201634198-d98c33ab-c3a2-4aaf-af04-9d0ea360f71b.png)

About the website state, can you force refresh without cache? On Google Chrome (and Windows) is something like Ctrl + F5. We believe this may be due to an aggressive bundle.js caching (not related to the dashboard state).

**Comment by gcthys** [comment]
Ctrl + F5 did the job, thanks!
Maybe something to mention in the user documentation?
