### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#238]
This is a better-safe-than-sorry question...
I deleted all the cookies on my laptop. When I try to log into NeoDash now, the option "Existing Dashboard" is faded out. If I hit "New dashboard" and connect to my Neo4j database, does my existing dashboard pop up then? Or have I lost everything (since my last backup 3 days ago)?
Just checking before I destroy my dashboard...
Thanks.

**Comment by BennuFire** [comment]
Hi @gcthys !

If you haven't persisted the state of your dashboard on a Database or a Json File I'm afraid you lost the progress made this last 3 days. I'm sorry about that. 

Btw, your previous background color request is on our backlog already :D 

Thanks!
