### ISSUE TITLE
Line Graph with DateTime Crashing

### ISSUE THREAD

**Issue by mbernardes** [neo4j-labs/neodash#243]
Hi,

I am trying to make a Line Graph using DateTime values as the X-Axis. Unfortunately this is making NeoDash crash with the error:

> Uncaught TypeError: Cannot read properties of null (reading 'getTime')

As an easy way of testing, I tried also making a 1-point LineGraph with the following code:

`return datetime("2019-06-01T18:40:32.142+0100") as Date, 1 as Value`

Unfortunately this results in the same error.

I would be very grateful for any hints on what I might be doing wrong.

Cheers,
Miguel

**Comment by BennuFire** [comment]
Hi @mbernardes!

Thanks for sharing this issue. In fact, there was a regression introduced recently not caught on our tests. 

This issue will be closed with https://github.com/neo4j-labs/neodash/pull/245 on 2.1.10 that's going to be release later today. 

Thanks, Miguel

Cheers,

Harold
