### ISSUE TITLE
Extend pull-down in Parameter Select to more than 5 results

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#251]
Please make the length of the pull-down search results to more than just the arbitrary 5, preferably to be determined in the Advanced Settings of the Parameter Select.
I have multiple persons in the database that have similar names: John Doe I, John Doe II, etc. and I want them all to be shown, not just the arbitrarily selected first five.
Thank you.

**Comment by GQ16** [comment]
Hey @gcthys , you can do this already in NeoDash if you have the latest version.
![image](https://user-images.githubusercontent.com/107271596/200026986-542a6f3a-ca26-423f-85e2-84f30653467b.png)

All you have to do is go to the Parameter Select Settings -> Advanced Settings -> Value Suggestion Limit, and then you can set the suggestions to whatever number you want!
![image](https://user-images.githubusercontent.com/107271596/200027268-849e850c-5983-41a6-aaae-2e981e1cc69f.png)

**Comment by gcthys** [comment]
Hi @GQ16 , thanks for bringing that to my attention. I had discussed this some time ago with Niels and had missed it in the update, sorry!
