### ISSUE TITLE
Line Chart Displays Non-Existent/Incorrect Data on 31st of April (A day that doesn't exist)

### ISSUE THREAD

**Issue by GQ16** [neo4j-labs/neodash#252]
- NeoDash version: 2.1.10
- Neo4j Database version: 1.5.2 (Enterprise)

**Steps to Reproduce:**
- Created a sales trend line chart in NeoDash highlighting sales in the months of April, May, and June.
- Here is the graph schema
![Customer 360 Conceptual Model (8)](https://user-images.githubusercontent.com/107271596/200009751-d34f7360-0d21-430c-a9fc-39c4ec9dcb2f.png)
- Here is the cypher query used to create the chart:
`MATCH (p:Party)-[:AGREED_TO]->(c:Contract)-[:HAS_LINE]->(cl:ContractLine)<-[iat:IS_ASSIGNED_TO]-(pr:Product),(cl)<-[:ACTUALIZED_ON]-(s:Shipment)-[:SHIPPED_ON]->(d:Date)
WHERE p.name = $neodash_party_name AND pr.type = $neodash_product_type AND d.id >= date("2022-04-01") AND d.id <= date("2022-06-30")
WITH sum(cl.quantity32e) AS Quantity32e,d.id.month AS Month, d.id.day AS Day
ORDER BY Month
WITH Day, collect([Month,Quantity32e]) AS Quantity_Month_Pairs
RETURN Day,
	Quantity_Month_Pairs[0][1] AS `April`,
	Quantity_Month_Pairs[1][1] AS `May` ,
        Quantity_Month_Pairs[2][1] AS `June`
ORDER BY Day`

**Expected behavior:**
- Here is how the chart looks when I extract the following query to CSV and make a line chart in Excel
Query: `MATCH (p:Party)-[:AGREED_TO]->(c:Contract)-[:HAS_LINE]->(cl:ContractLine)<-[:IS_ASSIGNED_TO]-(pr:Product),(cl)<-[:ACTUALIZED_ON]-(s:Shipment)-[:SHIPPED_ON]->(d:Date)
WHERE p.name = "Winfield Solutions LLC" AND pr.type = "UREA" AND d.id.year = 2022 AND d.id.month IN [4,5,6]
RETURN  d.id.month AS Month, d.id.day AS Day,sum(cl.quantity32e) AS Quantity32e
ORDER BY Month,Day`

**Correct** Chart in Excel:
![Proper Line Chart Excel](https://user-images.githubusercontent.com/107271596/200018186-9620c0cb-f068-4839-b282-e8269e3864e6.png)

**Correct** Table in Excel:
![Proper Table Excel](https://user-images.githubusercontent.com/107271596/200025998-4aa7f371-1c79-40fb-84ac-c925bb499fce.png)

**Actual behavior:**
**Incorrect** Chart in NeoDash (NOTE THERE VALUES ARE INTERMITTENTLY CORRECT BUT OFTEN WRONG SEE TABLE BELOW FOR MY THEORY):
![image](https://user-images.githubusercontent.com/107271596/200026580-ed7b9f74-46c5-40b7-bf37-c3294f471269.png)

**Incorrect** Table of Chart Values in Neo4j (NOTICE THE NEODASH BACKFILLS VALUES FOR DAYS WHERE THERE WAS NO SALE IN A GIVEN MONTH.[i.e. April 1-5, there was no sale, but this table shows that it is taking the May 1-5 sales and back filling them for April, then the June 1-5 sales are being back filled into May 1-5 because May went to April] THIS IS WHAT I BELIEVE IS CAUSING THE ISSUE):
![Neo4j Incorrect Table Drawing](https://user-images.githubusercontent.com/107271596/200026437-cf63ff98-51af-47b1-93b5-58fdbc2ca207.png)

Final Comment:
When I use the query I used to pull the data in Excel, this is the result I get; Note that there is no way for me to separate the lines, so this doesn't solve my issue either:
![image](https://user-images.githubusercontent.com/107271596/200026358-5d9b3490-6d60-46b1-b36d-3c8d3e5c7652.png)

Please fix this issue or make it possible to create additional lines in a line chart based on a PROPERTY and not just NODES.

**Comment by BennuFire** [comment]
Hi @GQ16 ,

This is not a Neodash error. Based on the results of your query, the line chart is correct. In general, Cypher errors can be addressed  on Neo4J Community https://community.neo4j.com/.

Keep in mind that you collect the values on  `WITH sum(cl.quantity32e) AS Quantity32e,d.id.month AS Month, d.id.day AS Day ORDER BY Month WITH Day, collect([Month,Quantity32e]) AS Quantity_Month_Pairs ` you are assuming that every day got some values to be summed.  If this is not the case, your collection will have less than 3 elements, therefore  `Quantity_Month_Pairs [3]` will  be null.

Thanks for using Neodash.

Harold
