### ISSUE TITLE
adding a visualization of the neo4j browser graph

### ISSUE THREAD

**Issue by ItamarSoffer** [neo4j-labs/neodash#253]
Hi,
is it possible to add a Visualization of the Neo4j Browser graph? 
This graph is very informative.

Thank you!

**Comment by ItamarSoffer** [comment]
and specifically - If I'm using : path = ()-[:REL_NAME*1..5]-() - be able to see all the nodes and relations.

**Comment by BennuFire** [comment]
Hi @ItamarSoffer ,

Neo4J Browser is a Neo4J product so we can't use that visualization on a Open Source Project. however, we do have a Graph Viz that already accomplish your wish.

Using 
![image](https://user-images.githubusercontent.com/7397411/200201266-880758d8-4852-4511-8b32-9986e83f0fa4.png)

I have:
![image](https://user-images.githubusercontent.com/7397411/200201282-cc697fda-607b-4070-b88a-d6920b6f1f78.png)

Thanks for using Neodash.
