### ISSUE TITLE
Support 2-Letter Country Codes and States/Provinces for Choropleth Map

### ISSUE THREAD

**Issue by GQ16** [neo4j-labs/neodash#261]
Hi, at the moment NeoDash supports choropleth maps using three letter country codes, but for my use case we're using two letter country codes, so if support could be added for that, it would be much appreciated.

Here is the IBAN table with the alpha-2 and alpha-3 codes for countries for your reference
and
Here are some of my country nodes at the moment just for the sake of clarity:
![image](https://user-images.githubusercontent.com/107271596/201150132-8f102dd8-b157-46ee-8125-b7bb7f36b8a7.png)

Also, consider allowing the Choropleth Map to show details of the states/provinces within the US, Canada, etc. using the same 3-char/2-char code convention!

**Comment by BennuFire** [comment]
Closed on 2.2.1

**Comment by adriens** [comment]
Great idea :heavy_heart_exclamation: Are 3-letters country codes also supported ?
![image](https://user-images.githubusercontent.com/5235127/217346463-de7d8c0e-92ff-4137-9e79-8bd5364eee61.png)

**Comment by BennuFire** [comment]
Hi @adriens ! 

Yes. It was already supported. This https://github.com/neo4j-labs/neodash/pull/284 PR extended it to alpha-3 and n3 codes too.
