### ISSUE TITLE
:whale:  Feature request > Neodash as a docker image :pray:  :whale: 

### ISSUE THREAD

**Issue by adriens** [neo4j-labs/neodash#262]
# :grey_question: Context

Actually we use Neo4J in two flavors : 

- Desktop version (eg. Windows users)
- Docker version (Programmers on linux)

While Neodash is available on the Desktop edition, we dont' know how to use Neodash while running a dockerized NeoJ instance
:point_right:  **we only can use the `Neo4J browser` in that case... and this what this issue is about.**

# :dart: Feature request

:point_right: We would like to be able to use Neodash and connect to a remote neo4J instance (for example running inside a contener), ideally packaged inside a docker image.

# :moneybag: Benefits

- Be able to automate dashboards delivery
- Create ready to user docker-compose projects
- Enhance developers experience UX

**Comment by maovidal** [comment]
The documentation tells how to run `neodash` in a `docker` container: https://github.com/neo4j-labs/neodash#running-neodash

**Comment by adriens** [comment]
Excellent :clap: thaks a lot for having pointed that to me :open_mouth:
