### ISSUE TITLE
:grey_question: Import dashboard (curl & docker) :nerd_face: 

### ISSUE THREAD

**Issue by adriens** [neo4j-labs/neodash#267]
# :grey_question: Context

We have started to create dashboards... and now we'd like to share/distribute them.

:point_right: Of course you can import them by clicking, but what I would like to achieve is to : 

> Be able to import them within shell, docker volume mount... so the enduser woud just have to clone a repo to be up and running.

# :dart: Question/Feature Request

Explain how, from within only script and Docker image we can import a dashboard into a NeoDash instance (at least how to achieve this with `curl`)

Thank you in advance for any help.

**Comment by boydkelly** [comment]
I'm just starting too.  But the dashboard can be saved as a json file.  I would like to get the syntax to load that file via cypher.

**Comment by BennuFire** [comment]
Guess I can close this one, no?

**Comment by alfredorubin96** [comment]
Closing this issue now that the dashboards are shareable, feel free to reopen it if you think this issue is still relevant!
