### ISSUE TITLE
Add cross-report filtering and interactivity

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#27]
Addition: a feature to let dashboard builders specify charts that are connected, e.g. filtering a report by clicking/selecting parts of the another visualization:
- Click on a table cell
- Click on Nodes/relationships in a graph
- Click on a bars in a bar chart

This click action should set a parameter `$neodash_xyz`, just like a parameter selection. The parameter can then be used in other reports.

**Comment by BennuFire** [comment]
Close on Extensions
