### ISSUE TITLE
Allow for sharing in standalone mode without password

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#279]
https://community.neo4j.com/t5/neo4j-graph-platform/neodash-standalone/m-p/62510
For self-hosted (and public) neodash deployments, there is a need for sharing a read-only dashboard with a login prompt before it, as described here.

**Comment by alfredorubin96** [comment]
I think this is done by sharing credentials inside the link, am i right @nielsdejong ?
