### ISSUE TITLE
Rule-based styling: node value = parameter

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#280]
In my graph representation, I would like the node which corresponds to the search parameter (in my case e.g. $neodash_name_name) to have a different colour. It would show the user where to start browsing through the graph.

At present, the Value field in the rule-based styling settings only accepts exact values. It would be a great addition if parameterized rule-based styling could be added.
Thanks.

**Comment by BennuFire** [comment]
Closed on 2.2.2
