### ISSUE TITLE
inquiry multi dashboards with same port in standalone mode

### ISSUE THREAD

**Issue by seonyh0** [neo4j-labs/neodash#287]
I have some question regarding calling neodash dashboard.

1. Is it possible to call two or more dashboards separately with the same port in standardone mode?

2. The message is displayed when the user id/password is set in standardone mode when the dashboard is inquired.
How to do to hide or erase the message ?
"Warning: NeoDash is running with a plaintext password in config.json."

3. Is it possible to display virtual nodes/relationships in Neodash ?

Thanks a lot !

**Comment by BennuFire** [comment]
Hi @seonyh0 ,

About 1. Dashboards itself live on the session storage of the client, and so far it's only one dashboard per session. You can always load a new dashboard from the left contextual menu

2. There's no way to hide but not using plaintext passwords in configs.

3. Yes, we can parse the results from a query that may include virtual (apoc) nodes/relationships.

**Comment by alfredorubin96** [comment]
I'll close this one, because now it's possible to open different dashboards using this three config parameters inside _config.json_:

  "standaloneAllowLoad": true,
  "standaloneLoadFromOtherDatabases": true,
  "standaloneMultiDatabase": true

Feel free to reopen this issue if needed
