### ISSUE TITLE
CSV file download

### ISSUE THREAD

**Issue by seonyh0** [neo4j-labs/neodash#288]
1. request to add function to download nodes, relationships properties to csv file in Graph Chart.

2. In the case of Table Chart, I can download the table list.
However, the UTF-8 characters are not decrypted when open thru Excel.
Request to change ecrypt format with 'UTF-8 BOM', not 'UTF-8'  when downloading to csv file.  BOM : EF BB BF (in hexa)

3. request to erase the one space(blank) after comma(,) that deleminate columns.
  Because of a blank,  a character " appears as a cell value in the cell when read in Excel.
    "ABC, "123"  ==>  "ABC","123"

Thanks a lot!!

**Comment by JonanOribe** [comment]
Could I be assign to this one?

**Comment by nielsdejong** [comment]
Sure! Thanks, I assigned you to the issue.

**Comment by JonanOribe** [comment]
PRs related to this issue on #381 and #372 (topic number 3)

**Comment by BennuFire** [comment]
Closed with 2.2.4
