### ISSUE TITLE
Advanced settings: add text colour setting

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#291]
Thanks for adding the Background Colour feature to the Advanced Settings: very useful!
However, the colour of all texts -except those text elements that are covered by Rule-Based Styling- is like that of the first Ford Model T: black, black and black :-).
This excludes the use of all dark backgrounds because they render the text illegible/invisible. 
Would it therefore be possible to add a Text Colour feature to the Advanced Settings?

**Comment by BennuFire** [comment]
Hi @gcthys , 

We added on 2.2.5 released today, an automatic change of text color on the _title_ for dark colors (based on the luma dashboard setting). On 2.2.6 this will be added too to the footer. Automatic change on chart content may require a bit more.
