### ISSUE TITLE
Can standalonePassword be set with environment variable in a non-Dockerized environment?

### ISSUE THREAD

**Issue by achantavy** [neo4j-labs/neodash#305]
Hi there, thank you for working on neodash. I spent some time playing with the YouTube introduction and it's very easy to get started. I am considering using it as part of a production deployment and had a question:

In a non-Dockerized environment, how can I specify the credentials to my Neo4j database without saving them in config.json?

I see that in a Dockerized environment I can set this through environment variables (https://neo4j.com/labs/neodash/2.2/developer-guide/configuration/), but I am not sure if this is possible with a non-Dockerized environment.

Thank you!

**Comment by alfredorubin96** [comment]
Yeah for sure this is possible to be set inside a non-dockerized variable, i'll close this issue.
