### ISSUE TITLE
standalone mode confusion

### ISSUE THREAD

**Issue by kbeiglCtgo** [neo4j-labs/neodash#308]
First of all: great project and thanx 

I'm having problems to understand (the combinations of) the configuration settings for the standalone mode in conjunction with the browser cache.

Let me go through the parameters consecutively:
With the command line:
`sudo docker run -it --rm -p 5005:5005 
-e standalone=true 
-e standaloneProtocol="neo4j+s" 
-e standaloneHost="neo.host.com" 
-e standalonePort="123" 
-e standaloneUsername="neo4j" 
nielsdejong/neodash`

.. the standaloneDatabase defaults to `'neo4j'` including the '' which is _probably a bug_.

Adding 
`-e standaloneDatabase="neo4j" `
.. works fine and shows protocol, host, port and database as _grayed_ entries!
username and password are still editable!

Observation: If you enter a password it will be remembered by the browser.

Next I add the `-e standalonePassword="secret"` and get prompted new/existing dashboard

- klick new

opens !editable! new dashboard

- klick existing

Then the connection dialog is _not grayed_ and everthing can be modified.
If I logon the default dashboard (Hi there, This is your first dashboard!) is presented.

problem: the browser is still using the remembered password, not the standalonePassword
solution: enter correct password manually

Next I add the `standaloneDashboardName="_Neodash_Dashboard" `

I get prompted new/existing dashboard

- klick existing

Then the connection dialog is _not grayed_ and everything, including dashboard can be modified.

problem: it always loads the dashboard from the browser cache, not the `standaloneDashboardName`

expected behavior: should logon and load `standaloneDashboardName` automatically

solution: use the editable dashboard to load another dashboard (from neo or file) as the 'existing' dashboard

Another issue is that storing a dashboard implicitly uses the name `"_Neodash_Dashboard"`
but if I store another dashboard another node is added with the same name
and I have to go through the same procedure to get the latest dashboard.

summary:
I think there is a conflict with the browser cache and 
to me it would make sense to clear the cached dashboard when loading or refreshing the page.
I clean the cached dashboard by clicking 'new dashboard' and stopping the server.

what am I doing wrong?
**I want our managers to enter the URL and immediately see the dashboard with loading reports** 
and if the dashboard node is updated the browser dashboard should get the latest and display it.
They should not be confused with two dialogs and 
they should see the latest dashboard and not the 'existing'.

And finally I can't load a `dashboard.json` via `standaloneDashboardURL`
but the might originate from the problems above analog to `standaloneDashboardName`.
BTW: is `file:///home/neodash/dashboard.json` also a valid URL ?

Maybe you could add some examples of valid combinations in the documentation :)

**Comment by alfredorubin96** [comment]
I will close this for now, feel free to reopen it if there is anything to add
