### ISSUE TITLE
Add support for display newlines (using `\n`) in single value charts

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#310]
## Feature request template

**Is your feature request related to a problem? Please describe.**
Single value reports are not able to display complex (multi-line) query results.

**Describe the solution you'd like**
Automatically insert newlines whenever the result string contains the `\n` escape sequence.

**Describe alternatives you've considered**
Trying to get a similar result with the escape sequence, or inserting HTML newlines, does not work.

**Comment by alfredorubin96** [comment]
Closed because fixed with the issue #387
