### ISSUE TITLE
Extend 'Raw JSON' report types to render processed json and YML trees

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#315]
**Is your feature request related to a problem? Please describe.**
Currently the Raw JSON report type returns the direct output from the Neo4j driver:

```
[
  {
    "keys": [
      "X",
      "Y"
    ],
    "length": 2,
    "_fields": [
      "A",
      {
        "low": 123,
        "high": 0
      }
    ],
    "_fieldLookup": {
      "X": 0,
      "Y": 1
    }
  }
]
```

It will be useful to also render a clean, processed JSON structure (with the _fields and _fieldLookup keys merged) to be more human-readable.

**Describe the solution you'd like**
For the example above, we can create an advanced report setting `returnFormat` with three settings `['raw', 'json', 'yml']` that determines the output.

Example for `json` for the data above:
```
{
  "X": "ABC",
  "Y": 123
}
```
Example for `yml` for the data above:
```
X: ABC
Y: 123
```

**Comment by BennuFire** [comment]
Closed with 2.2.4
