### ISSUE TITLE
Refactor Graph Visualization component to split rendering/processing logic

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#318]
- Separate data processing and rendering functionality into separate files. E.g. (charts/graph/Graph.tsx & charts/graph/GraphHandler.ts)
- Move generic data processing logic to ChartUtils.ts

**Comment by alfredorubin96** [comment]
Didn't you refactor the graph viz already? Is this issue still relevant?

**Comment by nielsdejong** [comment]
Yep this is done, thanks for the reminder!
