### ISSUE TITLE
Heatmap library throws an error

### ISSUE THREAD

**Issue by JonanOribe** [neo4j-labs/neodash#332]
- NeoDash version: 2.2.1

- **Steps to reproduce**
After launch yarn run dev, I found an error on the loading of the heatmap library.

- Expected behavior
The library should be loaded correctly.

- Actual behavior
After project deployment, this error is throwed.

![image](https://user-images.githubusercontent.com/11914201/216270556-0e4d1391-c616-472e-9f69-3370e4affa98.png)

**Comment by nielsdejong** [comment]
Hi @JonanOribe , this appears to be an issue when running the app in development mode on Windows systems as I've seen in the past (I think it has something to do with folder seperators (`/` v.s. `\`). @BennuFire had the same issue, maybe he has some idea how to fix this one?

**Comment by BennuFire** [comment]
Hi @JonanOribe ,

This error is related to https://github.com/facebook/create-react-app/pull/11752 . In general it's not harmful so I just added one workaround on https://github.com/neo4j-labs/neodash/pull/343 that will ignore this kind of annoying warnings. 

We will push this on dev early this week. I hope you will survive till then :D 

Thanks for reaching us and eager to see your PR
