### ISSUE TITLE
Latest Update Changed Grouped Stacked Bar Charts - Put them back to how they were!

### ISSUE THREAD

**Issue by GQ16** [neo4j-labs/neodash#339]
I have a bar chart in NeoDash that used to look like this:
![image](https://user-images.githubusercontent.com/107271596/216726999-c196bbde-2963-42f9-a588-ec7b41cd24f6.png)

But after the latest NeoDash Update, it looks like this:
![image](https://user-images.githubusercontent.com/107271596/216727111-eb1f87d0-f2ac-4b1c-b823-7b83fee82382.png)
and I can't get it to change to what I want! Please let me know how to get it back to that look. Note how now the legend is very confusing/useless and the visual is no longer as clear in differentiating the different groups.

**Comment by BennuFire** [comment]
Hi @GQ16!

We are aware of this change and we will provide a fix early next week. I'm sorry to hear that this change affected you.

Harold

**Comment by nielsdejong** [comment]
Resolved by https://github.com/neo4j-labs/neodash/pull/343
