### ISSUE TITLE
Full screen symbol gone

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#340]
Since release v2.2.2-pro the symbol for full screen has gone from the report panels. It can now only be accessed from the edit mode...

**Comment by nielsdejong** [comment]
Hi @gcthys ,
By popular request we have changed the option to make a report fullscreen from a global to a local setting. You can now use the advanced settings of a single report to show the fullscreen button for that report only. 

Could you see if that works for you? Testing locally in viewer mode it seems to work okay for me.

**Comment by gcthys** [comment]
Hi @nielsdejong ,
thanks for pointing that out to me. 
It does indeed make sense to make it local. Works fine.
Maybe add a line about this to the User Guide?
