### ISSUE TITLE
Bug working with Husky on PR with Windows 11

### ISSUE THREAD

**Issue by JonanOribe** [neo4j-labs/neodash#342]
I was having the error of the image when trying to do a commit against the repository

![image](https://user-images.githubusercontent.com/11914201/216973469-422f31b5-db46-4750-96bb-56324942eae9.png)

Looks like is something related with husky precommit, because if I comment the file, everything runs fine. So probably the error has something to do with tihs line `. "$(dirname -- "$0")/_/husky.sh"`

![image](https://user-images.githubusercontent.com/11914201/216975013-05965603-faa5-4201-b1dc-1167f2a1bdd1.png)

Any idea how to adapt husky to different path systems?

**Comment by bastienhubert** [comment]
Hey @JonanOribe, 

Sorry for the late answer, I made [a PR](https://github.com/neo4j-labs/neodash/pull/385) that probably should fix your problem, can you let me know if this fix is working on your side please?

**Comment by BennuFire** [comment]
Closed with 2.2.4
