### ISSUE TITLE
The new Property Display Name Override does not reset automatically

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#347]
When I set Property Display Name Override to ON, then change e.g. $neodash_name_name into $neodash_name_text (another property of the same node) and then switch Property Display Name Override to OFF again, the parameter remains set to $neodash_name_text.

I figured out that I need to manually reset the Name to the original value before I switch to OFF. I would be handier if this were done automatically. Or else, please indicate this clearly in the User Manual. Thank you.

**Comment by nielsdejong** [comment]
Hi @gcthys ,

We pushed a quick fix for this in version 2.2.3 which was release today.
Thanks for letting us know!
