### ISSUE TITLE
[Feature Request] Allow iso_alpha_2 code for the Choropleth Map report

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#354]
**Is your feature request related to a problem? Please describe.**
Currently, you have to use the country code iso_alpha_3 to color the map in the Choropleth Map report. For example (FRA for France). But, the Choropleth Map report can't handle the country code iso_alpha_2. For example (FR for France).

**Describe the solution you'd like**
Allow the country code iso_alpha_2 for the Choropleth Map report.

**Describe alternatives you've considered**
No solution right now?

**Additional context**
Nothing to add.

Best regards,
Cobra

**Comment by BennuFire** [comment]
Hi @Cobra5197

What version are you using? I remember this being introduced on 2.2.1. We also added n3 codes.

**Comment by Cobra5197** [comment]
Hi @BennuFire 

I'm using the browser version (2.2.3-extended). It works with iso_alpha_3 but not with iso_alpha_2.

**Comment by BennuFire** [comment]
Hi @Cobra5197,

Have you set the Advanced setting for the Choropleth into 2L?

**Comment by Cobra5197** [comment]
Oh I didn't see it, my fault!

Thank you:)

**Comment by adriens** [comment]
:rocket:
