### ISSUE TITLE
Report Actions buttons not clickable on deployed version

### ISSUE THREAD

**Issue by Iqra840** [neo4j-labs/neodash#355]
When working with report actions locally, the buttons work and respond as expected; however, as shown in the screenshots, the buttons are disabled when I deploy it through GitHub pages. The report actions extension is enabled in both and both Neodash and the hosted dashboard are running on v. 2.2.1, with Neo4j Desktop on v. 1.5.6.

![ra1 (2)](https://user-images.githubusercontent.com/54781026/217977944-302ebe54-0f60-4d01-94b3-b66858c112df.PNG)
![Screenshot 2023-01-27 at 5 12 19 PM (1)](https://user-images.githubusercontent.com/54781026/217977938-f3a88cb7-ccd1-402a-9427-515e93467065.png)

**Comment by BennuFire** [comment]
Hi @Iqra840 !

This is not a bug. Neo4J Profesional Services extensions are free to use only on Neo4J Desktop and [Neo](http://neodash.graphapp.io/)
