### ISSUE TITLE
Bar Chart grouping issue

### ISSUE THREAD

**Issue by dstaehler** [neo4j-labs/neodash#359]
Hello neoDash Team, 
after updaten to 2.2.3 I experiance problems with the Bar Charts when using "Group" mode. The legend will not be populated correctly and some of the color labels just stay black.

Is this a known bug?

Any help greatly appreachiated

**Comment by harsha5500** [comment]
Hello,

I too am using the 2.2.3 version and facing a similar issue with respect to colours and legend. It seems I loose the the mapping when there are 0 values in case of grouping. I am not able to find the mechanism for assignment. I tried setting the min value in advanced mode and still am not able to force the colours and legend to fix themselves.

<img width="358" alt="Screenshot 2023-05-29 at 13 35 08" src="https://github.com/neo4j-labs/neodash/assets/1305937/7147b55d-d545-4ee9-b57e-5bdf2fcd8f42">

**Comment by alfredorubin96** [comment]
Is this issue still revelant with respect of the latest version?

**Comment by harsha5500** [comment]
Hello, No after I upgraded to the latest version this is not happening anymore. Thank you very much.
