### ISSUE TITLE
[Feature Request] Add zoom to Choropleth Map report

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#360]
Hello,

I would like to be able to zoom on the Choropleth Map report like map report allow it.
Because it is not easy to see countries with a small surface.

Regards,
Cobra

**Comment by alfredorubin96** [comment]
Hi @Cobra5197, we offer the zoom feature on the Area Map. I know there is some redundancy between the Choropleth and the Area Map, we'll try to cover it soon. Feel free to reopen this issue if needed.
