### ISSUE TITLE
Bar chart with stacking + grouping + legend does not assign legend colors for zero-values

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#368]
For NeoDash 2.2.3, when the first group of bars has a zero value for one or more of the categories, a black color is incorrectly assigned to the group legend. Colors should be inferred also when the value for the first category value is zero.
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/1754968/220446157-18ee06dc-2063-4599-8208-e2aa354d5c3c.png">

**Comment by alfredorubin96** [comment]
@nielsdejong is this fixed? Seems pretty important, we should take it sooner than later

**Comment by nielsdejong** [comment]
Hi @alfredorubin96 yes this is resolved! Thanks for checking
