### ISSUE TITLE
Hiding columns in Table does not work

### ISSUE THREAD

**Issue by NanisTe** [neo4j-labs/neodash#374]
- NeoDash version: v2.2.3-extended
- Neo4j Database version: 4.4.3 (Community).

**Steps to reproduce**
Create a table and add columns sizes activate all functions like reload, image export, csv export, and create column width, color the table, create reactive buttons on one column. Try to hide a column without button. Try to hide a column with button.

Expected behavior
When selecting Hide on one column that column should hide.

Actual behavior
Nothing happens.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/17549266/222400947-f1098b5f-df08-42c2-adc5-c5772acc3488.png">

<img width="251" alt="image" src="https://user-images.githubusercontent.com/17549266/222401040-fbe231ae-14ae-4851-9df4-e74b57ac2ea7.png">

<img width="257" alt="image" src="https://user-images.githubusercontent.com/17549266/222401151-04154ca0-784b-4741-8b6a-5060edf4cd81.png">

**Comment by JonanOribe** [comment]
Could I take this one?

**Comment by nielsdejong** [comment]
Sure, thanks a lot @JonanOribe !
