### ISSUE TITLE
Add set report actions to bar and line charts

### ISSUE THREAD

**Issue by CHYoon8** [neo4j-labs/neodash#376]
## Feature request template

**Is your feature request related to a problem? Please describe.**
Please add set report actions to graphs such as a bar chart.
When you clicked on a bar or a dot on a line chart, it transfers the x or y axis value to a global variables.

**Comment by CHYoon8** [comment]
Could you please tell me when we might expect this content to be implemented?

**Comment by BennuFire** [comment]
Hi @CHYoon8 

This is a valid enhancement and it will be considered for one of the next releases. We just released a bunch of new things recently and we are waiting for it to be ingested before adding new things. No promises but it may be part of Neodash before the end of the month.

Thanks for using it :)

**Comment by alfredorubin96** [comment]
I'll close this issue because we offer the report action for the Bar Chart, but i'll file a new issue for the Line chart to add report actions also there.
