### ISSUE TITLE
Does Neodash have proxy for connecting neo4j server

### ISSUE THREAD

**Issue by duongphannamhung** [neo4j-labs/neodash#377]
Currently, I'm using Neo4j Community 5.5 and Neodash 2.2 both with docker and in the same network (bridge driver). I've exposed and mapped Neodash with localhost:5005 so I can reach it from localhost. But unless I map Neo4j to localhost (which I don't want to cause of privacy), I can't connect it from Neodash. 
So do you have proxy for connecting through you to Neo4j server. Thanks alot.

**Comment by BennuFire** [comment]
Hi @duongphannamhung ,

Neodash is a light client application that interacts directly with the DB from the user station through a JavaScript driver connection. If the Neo4J bolt endpoint is not reachable from the client terminal, Neodash will not work. Unfortunately we don't ship (at the moment) any backend proxy that may allow this. 

In the future, (not strictly near one) we would separate the connection to the db logic from the client so connections get handled by a middleware server.
