### ISSUE TITLE
Cannot plot more than one point with the same coordinates on a map

### ISSUE THREAD

**Issue by minottimat1** [neo4j-labs/neodash#380]
## Guidelines
Please note that GitHub issues are only meant for bug reports/feature requests. 

Before creating a new issue, please check whether someone else has raised the same issue. You may be able to add context to that issue instead of duplicating the report. However, each issue should also only be focussed on a _single_ problem, so do not describe new problems within an existing thread - these are very hard to track and manage, and your problem may be ignored. Finally, do not append comments to closed issues; if the same problem re-occurs, open a new issue, and include a link to the old one.

To help us understand your issue, please specify important details, primarily:

- NeoDash version: X.Y.Z
- Neo4j Database version: X.Y.Z (Community/Enterprise/Aura).

- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) screenshots, drawings, etc.

**Comment by BennuFire** [comment]
Hi @minottimat1 ,

Have you tried with the Advanced Configuration, Cluster Markers ON? I this solves your problem, I can add a default ON with a small radius distance.
