### ISSUE TITLE
Duplicate node in graph result if the node has multiple labels

### ISSUE THREAD

**Issue by mehdi-jafari** [neo4j-labs/neodash#389]
- NeoDash version: v2.2.3-extended
- Neo4j Database version: Aura

- **Steps to reproduce**
      - Created nodes with 2 labels in AuraDB
      - Create cypher query to show them in Graph. the result includes the same node, twice. one for each label. 
- Expected behavior
     - the result includes only one node as requested in the cypher query. the same as if it returns in table format.
- Actual behavior
    - the result includes 2 nodes one per label.

**Comment by BennuFire** [comment]
HI @mehdi-jafari ,

Thanks for sharing this with us. I think I understand your bug but in order to be 100% sure, can you share the query you use on the graph chart while looking for this node?

Thanks,

Harold

**Comment by mehdi-jafari** [comment]
Hi Harold,

Thank you for your quick response.

here is the query :

MATCH p=()-[:FALLS_UNDER*]->(n:Category)-[:FALLS_UNDER]->(:SubCategory) where n.Name = $neodash_category_name return p

Please let me know if you need further information.

Regards,
Mehdi Jafari


________________________________

**Comment by BennuFire** [comment]
Hello hello!

Can you share some screenshots on this? Specially on the node that's duplicate. I'm trying to reproduce this. If you have a creation script that may allow me to recreate this easily, it will be highly appreciated .

**Comment by mehdi-jafari** [comment]
I can reproduce it in any case that has more than one label. do you still need screenshots?

**Comment by BennuFire** [comment]
Hi @mehdi-jafari 

I tried to reproduce this before our next release with no  successful results. 

I used this as dataset
`
CREATE(a:A:B {name : "node1"})-[:REL]->(c:C {name : "node2"})
WITH a
CREATE(:TEST {name : "n1"})-[:RR]->(:TEST {name : "n2"})-[:RR]->(:TEST {name : "n3"})-[:RR]->(a)
`

However  `MATCH p=()-[:RR*]->(n)-[e:REL]-(m) RETURN p` it's not failing. I may need some extra input about your data or a replicator.

Thanks
