### ISSUE TITLE
[Feature Request] Use the first row of the table as column keys

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#428]
Hello,

**Is your feature request related to a problem? Please describe.**
I ran into the problem when my query had two columns: one for column names and one for values. Then I transposed it to only have one line and hoped it would take the first line for the column names.

**Describe the solution you'd like**
I would like to have an option in the table settings that allows me to use the first row of the table as the column names.

**Describe alternatives you've considered**
Right now, I no longer transpose the table.

Best regards,
Cobra

**Comment by mariusconjeaud** [comment]
If enabled through a setting, it can probably be parsed from the query result, isolating the first row and passing it as the column keys in place of the variable names returned by Cypher.

**Comment by bastienhubert** [comment]
@Cobra5197 Deployed in 2.3.1 :)
