### ISSUE TITLE
Request to add scrolling feature for content exceeding panel boundaries

### ISSUE THREAD

**Issue by CHYoon8** [neo4j-labs/neodash#430]
Could you please consider adding a feature to enable users to view the remaining content beyond the scope of a panel, in case the information displayed in a single value or table exceeds the panel's boundaries, via horizontal or vertical scrolling? Thank you.

**Comment by brahmprakashMishra** [comment]
Hi. I have implemented a feature such that if the table content exceeds 2 rows, the text is replaced with an ellipsis and when mouse is hovered over the cell, a popover shows up with the full content.

**Comment by alfredorubin96** [comment]
HI @CHYoon8 , i'll close this issue because the table offers the option Wrap overflowing content. Please feel free to reopen this issue if needed.
