### ISSUE TITLE
Request for Interaction Feature to Filter Data in Bar and Line Charts

### ISSUE THREAD

**Issue by CHYoon8** [neo4j-labs/neodash#431]
I would like to request the addition of an interaction feature where users can filter data using the x-axis or y-axis data of the selected section, when they click on a bar or line in a bar chart or line chart. This would greatly enhance the functionality of the charts. Thank you.

**Comment by BennuFire** [comment]
Isn't this the same as https://github.com/neo4j-labs/neodash/issues/376 ?

**Comment by CHYoon8** [comment]
Yes it is the same. I thought you may have forgotten the previous issue. Thank you for your response and help.Sent from my Galaxy
-------- Original message --------From: Harold Agudelo ***@***.***> Date: 5/2/23  10:26  (GMT-07:00) To: neo4j-labs/neodash ***@***.***> Cc: CHYoon8 ***@***.***>, Author ***@***.***> Subject: Re: [neo4j-labs/neodash] Request for Interaction Feature to Filter Data in Bar and Line Charts (Issue #431) 
Isn't this the same as #376 ?

**Comment by alfredorubin96** [comment]
I'll close this issue because we offer the report action for the Bar Chart, but i'll file a new issue for the Line chart to add report actions also there.
