### ISSUE TITLE
Free text parameter select not accepting user inputs

### ISSUE THREAD

**Issue by lavkan** [neo4j-labs/neodash#435]
- NeoDash version: Neodash desktop version (desktop version 1.5.7 on Mac)
- Neo4j Database version: 5.3

- **Steps to reproduce**
- Expected behavior of free text parameter select should allow users to input free text in the text bar 
- Actual behavior: User inputs are not allowed, but see a default message "No selection specified"
- Current fix: If a working parameter select report is cloned and replaced by free text, it accepts user inputs!

Reference: https://community.neo4j.com/t/could-not-get-free-text-parametrization-to-take-in-user-inputs-in-neodash/62371

**Comment by BennuFire** [comment]
Solved on 2.3
