### ISSUE TITLE
Concatenating a URL and a regular string turns the whole newly created string into a url

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#438]
I have 2 properties:
s.url which is a string containing a url
r.date which is a string containing a year

I want to concatenate these into one string, where the s.url-component stays a URL and the r.date component stays a string, but with the "+"-operator as well as with apoc.text.join([s.url, ', ', r.date], ' ') the whole output, including the comma and the date, is turned into a URL:
![Schermafbeelding 2023-05-11 110511](https://github.com/neo4j-labs/neodash/assets/68611501/08395cee-0e4b-401b-9ddf-cdd3672e21a3)
but this should be returned:
![Schermafbeelding 2023-05-11 110831](https://github.com/neo4j-labs/neodash/assets/68611501/7b773b1f-c346-41eb-a314-612f13b5ed2a)

I ran the query in Browser and it works fine there, so this must be an issue in NeoDash.

**Comment by gcthys** [comment]
??? Anybody ???

**Comment by alfredorubin96** [comment]
Thank you for the input. It looks like it's possible to use commas into URLs, so we don't see a reason to parse the string and store it in two different entries. What we can suggest is to return the same value splitted in two columns, if for example you're using a Table Chart.
