### ISSUE TITLE
Map type cannot show the property of the node

### ISSUE THREAD

**Issue by heguangqing** [neo4j-labs/neodash#444]
- NeoDash version: 2.2.4 and 2.2.5
- Neo4j Database version: 4.4.20 (Enterprise).

- **Steps to reproduce**
- Create a map page, using cypher command like match(n) return n to show the node has latitude and longitude properties.
- click the node to show the detailed property data

- Expected behavior
-The property data should be shown 

- Actual behavior
All the property data are shown as:

property1: | value.properties[k].toString()
latitude: | value.properties[k].toString()
longitude: | value.properties[k].toString()

Additionally, include (as appropriate) screenshots, drawings, etc.
![Uploading maperror.jpg…]()

**Comment by BennuFire** [comment]
Solved on 2.3
