### ISSUE TITLE
Creating Nodes on NeoDash

### ISSUE THREAD

**Issue by francoacn** [neo4j-labs/neodash#449]
Hi all,

I was wondering it there's a chance to create nodes on the graph visualization reports of NeoDash.
Indeed, it seems that it's possible to create only relationships at the moment.

Thanks!

**Comment by alfredorubin96** [comment]
Hi, to create a node, you can use the Form chart. To use it remember to enable its extension. I'll close this issue but feel free to reopen it if needed.
