### ISSUE TITLE
OpenAi query Translator

### ISSUE THREAD

**Issue by AleSim94** [neo4j-labs/neodash#455]
Description: The objective is to "productionize" the experimental/nlp-query branch. This should be part of the 2.3.0 release!

- [ ] Create a central component that has the responsibility to handle the translation logic from natural Language -> Cypher
- [ ] Add retry policy if the query is not valid 
- [ ] update/enhance the system prompt logic
- [ ] define an abstract model for an AI Client(OpenAI, Bard, etc)
- [ ] define a reducer for this extension
- [ ] define a minimum way to plug the extension to the main application

**Comment by mariusconjeaud** [comment]
PR #482

**Comment by BennuFire** [comment]
Closed on 2.3
