### ISSUE TITLE
[Feature Request] Be able to disable the warning in standalone mode

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#460]
Hello,

**Is your feature request related to a problem? Please describe.**
In standalone mode, we would like to be able to hide the warning message: _Warning: NeoDash is running with a plaintext password in config.json._

![image](https://github.com/neo4j-labs/neodash/assets/47223105/747c09fe-4883-46b8-92e3-90d172145363)

**Describe the solution you'd like**
Have a setting somewhere to disable/enable the warning. It can be enabled by default.

Best regards,
Cobra

**Comment by brahmprakashMishra** [comment]
We intend to take this up shortly (maybe in 2 weeks time). Stay tuned!

**Comment by brahmprakashMishra** [comment]
Some delay on this from our end - I think it'll be a few more weeks (1-1.5 months) before we can get to it.

**Comment by achantavy** [comment]
+1 would like to see this feature too

**Comment by Cobra5197** [comment]
Any news on this feature?

**Comment by Cobra5197** [comment]
You can now add the parameter "standalonePasswordWarningHidden": true in the latest version of NeoDash so I close the request.
