### ISSUE TITLE
Version Upgrade for React-Testing-Library and CoreJs

### ISSUE THREAD

**Issue by brahmprakashMishra** [neo4j-labs/neodash#471]
Getting the below issues, should I submit a PR for updated dependencies? 

` => => # warning material-ui-color-picker > recompose > fbjs > core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Becau
 => => # se of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility is
 => => # sues. Please, upgrade your dependencies to the actual version of core-js.
 => => # warning use-neo4j > react-testing-library@8.0.1: 🚨  react-testing-library has moved to @testing-library/react. Please uninstall react-testing-library and install @testing-li
 => => # brary/react instead, or use an older version of react-testing-library. Learn more about this change here: https://github.com/testing-library/dom-testing-library/issues/260 T
 => => # hanks! :)
`

**Comment by BennuFire** [comment]
Hi @brahmprakashMishra,

Thanks for being active around here. We will not use that picker anymore from our next 2.3 release so I guess there's no need for this. You can already test that on our dev branch.

Regards,

Harold

**Comment by brahmprakashMishra** [comment]
Thanks Harold for the update!
