### ISSUE TITLE
linking to a specific page using ?page= on the URL not functioning as expected

### ISSUE THREAD

**Issue by pdrangeid** [neo4j-labs/neodash#477]
When using ?page=# on the URL to directly connect to a particular page- it does not work.
I'm guessing it it is maybe getting over-ridden by the settings in the dashboard config (from the _Neodash_Dashboard node) page=x
I would expect that if you provide a page= on the URL that should override any default config in the dashboard config.

I know this USED to work as expected - at least I recall having installations in the past where the page= behavior worked, so I'm not sure if a recent update changed the functionality

- NeoDash version: 2.2.5

**Comment by alfredorubin96** [comment]
Closing this issue because will be fixed inside Neodash commercial, leaving the issue #373 for further discussion
