### ISSUE TITLE
[Feature Request] Multiple dashboards for one connection

### ISSUE THREAD

**Issue by Cobra5197** [neo4j-labs/neodash#488]
Hello,

**Is your feature request related to a problem? Please describe.**
We built multiple dashboard based on the same DBMS so we have multiple JSON dashboard files.

**Describe the solution you'd like**
We would like to be able to have multiple dashboard for the same connection. Visually, you could add a drop-down with all the dashboards. Like this, the use will have the possibility to switch between dashboards quickly and we won't have to deploy each dashboard side by side.

**Describe alternatives you've considered**
We have to deploy multiple standalone dashboard if we want to have all of them at the same time.

Best regards,
Cobra

**Comment by pganzoncba** [comment]
+1 upvote

**Comment by alfredorubin96** [comment]
Thank you for the suggestion @Cobra5197, i have a question: isn't this fixed with the sidebar, or you think there is still something to do?

**Comment by Cobra5197** [comment]
Yeah indeed, it's solved!
