### ISSUE TITLE
:dark_sunglasses: Dark theme :black_heart: 

### ISSUE THREAD

**Issue by adriens** [neo4j-labs/neodash#509]
## Feature request template

I would like to be able to get a dark theme to make UX better and more readable.

**Comment by BennuFire** [comment]
Hi @adriens !

We are waiting for native support of this on our internal component provider. In the meantime, have you played with the new Style Config? That may be a good starting point for the dark theme.

**Comment by adriens** [comment]
> have you played with the new Style Config? That may be a good starting point for the dark theme.

We have played with the theme at the chart level, but found it complicated to maintain a consistent style at the dasboard level. Would you have any annoucement to share or wiki post about the "new Style Config".
Meanwhile, we can wait for the _internal support provvider_ 👍

**Comment by BennuFire** [comment]
Hi @adriens ,

I'm fixing the docs with https://github.com/neo4j-labs/neodash/pull/544 

Are you using Neodash built and deployed by you or directly on http://neodash.graphapp.io/ ?

**Comment by adriens** [comment]
Hi @BennuFire , we are using neodash : 

- `10%` from Docker
- `90%` within Neo4J Desktop on the developer workstation, just next to the locally running Neo4J instance

Does it answer the question ?

**Comment by BennuFire** [comment]
Hi @adriens ,

So https://github.com/neo4j-labs/neodash/pull/544 add into the docs some details but long story short, if you go to your local Desktop Neodash folder (e.g for me it's C:\Users\agude\.Neo4jDesktop\graphApps\_global\neodash)

Inside the dist folder there's the style.config.json file.

If you set the json with the right values you can get the dark theme or even your own style look and feel.

In example:


{
    "DASHBOARD_HEADER_COLOR" : "#F3F3F0",
    "DASHBOARD_HEADER_BUTTON_COLOR" : "#009999",
    "DASHBOARD_HEADER_TITLE_COLOR" : "#00C1B6",
    "DASHBOARD_PAGE_LIST_COLOR" : "#F3F3F0",
    "DASHBOARD_PAGE_LIST_ACTIVE_COLOR": "#009999",
    "style": {
      "--palette-light-neutral-bg-weak" : "243, 243, 240"
    }
  }

**Comment by adriens** [comment]
ok, so for now, it is not part of the long term conf... which would be part of the exported `json` ?

**Comment by BennuFire** [comment]
That's a style specific conf that should help people create their own theme.

Feel free to build this branch https://github.com/neo4j-labs/neodash/pull/552 that already contains a first version of the dark mode.

**Comment by BennuFire** [comment]
Released on 2.3.2

**Comment by adriens** [comment]
🚀 
![image](https://github.com/neo4j-labs/neodash/assets/5235127/c965f546-0023-4590-8638-a065bd54cc16)
