### ISSUE TITLE
Bar Graph Legend Color shows black and interchanging colors within the graph

### ISSUE THREAD

**Issue by akshaykagarwal** [neo4j-labs/neodash#518]
- NeoDash version: 2.3.0
- Neo4j Database version: 4.4.19 (Enterprise).

I am building a stacked bar graph. The problem occurs when I enable legend to be displayed. In the legend, I see many entries marked with black color (instead of their actual color). Example image is below:

![image](https://github.com/neo4j-labs/neodash/assets/100434980/c034d2f8-e91d-4985-9ac2-3120406f3389)

The setting for this particular graph is :

> {
          "title": "#tasks assigned per month per person",
          "query": "match(i:Issue)-[:AssignedTo]-(a:Assignee)\n//WHERE i.type = \"Bug\"\nWHERE a.name <> \"null\"    \nWITH apoc.date.parse(i.createdOn, 'ms', 'dd/MMM/yy h:mm a') AS milliseconds,i,a\nWITH date(datetime({epochmillis: milliseconds})) AS createDate, i, a\nWITH apoc.temporal.format(createDate, \"yyy\") AS Year, apoc.temporal.format(createDate, \"MM\") AS Month,i,a\nWHERE Year >= \"2020\" AND Year < \"2021\"\nRETURN Month, a.name AS AssignedTo,count(i) AS NumReq\nORDER BY Month\n\n\n",
          "width": 6,
          "height": 2,
          "x": 0,
          "y": 12,
          "type": "bar",
          "selection": {
            "index": "Month",
            "value": "NumReq",
            "key": "AssignedTo"
          },
          "settings": {
            "type": "Node Property",
            "barValues": false,
            "legend": true,
            "labelRotation": 0,
            "hideSelections": true,
            "fullscreenEnabled": true,
            "downloadImageEnabled": true,
            "marginBottom": 50,
            "marginLeft": 100,
            "marginRight": 300,
            "showOptionalSelections": true,
            "groupMode": "grouped",
            "colors": "nivo",
            "minValue": 0
          },
          "database": "datadb",
          "id": "542a6250-c3d3-4623-af22-570523160004"
        }

I would have expected that the second entry in the legend would show the right color instead of black. This is just one example. Also, in the case where the entry "88a..." is only present, it takes the color of the entry "39f..." instead. This should not happen as well. See image below for this:

![image](https://github.com/neo4j-labs/neodash/assets/100434980/9072bd17-c652-4b00-8a3b-1c0977c7cb96)

**Comment by akshaykagarwal** [comment]
Any update on this bug please?

**Comment by bastienhubert** [comment]
Hi @akshaykagarwal, I will take a look by the end of the week and will keep you updated

**Comment by bastienhubert** [comment]
I took a look but unfortunately I won't be able to solve this quickly, I will keep you updated, probably in September

**Comment by BennuFire** [comment]
Solved here https://github.com/neo4j-labs/neodash/pull/626
 To be merged on our next release

**Comment by alfredorubin96** [comment]
Closed this issue because it has been fixed in #626
