### ISSUE TITLE
azure openai api key

### ISSUE THREAD

**Issue by maaly77** [neo4j-labs/neodash#530]
## Guidelines
Please note that GitHub issues are only meant for bug reports/feature requests. 

Before creating a new issue, please check whether someone else has raised the same issue. You may be able to add context to that issue instead of duplicating the report. However, each issue should also only be focussed on a _single_ problem, so do not describe new problems within an existing thread - these are very hard to track and manage, and your problem may be ignored. Finally, do not append comments to closed issues; if the same problem re-occurs, open a new issue, and include a link to the old one.

To help us understand your issue, please specify important details, primarily:

- NeoDash version: 2.3
- Neo4j Database version: 4.4.9 (Community)

- **Steps to reproduce**
I tried to use azure openai key to use the NLP feature. It seems to work only with openai api key but not azure openai key

**Comment by BennuFire** [comment]
Solved with https://github.com/neo4j-labs/neodash/releases/tag/2.3.1
