### ISSUE TITLE
🐛 Table widget does not display row that contain field with "false" value

### ISSUE THREAD

**Issue by adriens** [neo4j-labs/neodash#534]
# ❔ About

Within the following versions:

- Neo4J : `5.7.0`
- Neodash : `2.3.0`

The table widget does not display the rows that have a boolean field with the `false` value : we only see the ones with the `true` value.

For example, with the following cypher:

```cypher
MATCH (u:UO)-[m:MAINTAINS]->(n:Application)
WHERE u.code = $neodash_uo
RETURN n.id_app,n.is_run_contenerized,
    n.docker_registry_name,
    u.code,
   u.nom
```

The consequence is that for example, we cannot style the rows

Below the result:

![image](https://github.com/neo4j-labs/neodash/assets/5235127/05538cd4-d456-4711-89a1-6fbb2f908c1d)

**Comment by bastienhubert** [comment]
Hey Adrien, I'm on it :)

**Comment by adriens** [comment]
So you could manage to reproduce it ?

**Comment by bastienhubert** [comment]
Yes quite easily by writing a query like `RETURN false AS falseValue, true AS trueValue` in the table component

**Comment by adriens** [comment]
Nice shot LOOOOL

**Comment by adriens** [comment]
Thanks a lot for the quick fix. We're upgrading it now and giving it a try ⚡

**Comment by bastienhubert** [comment]
You are welcome 😁

**Comment by adriens** [comment]
Here we GO:

- ✔️ Tested
- 🚀 Validated

Thank you all 👏
