### ISSUE TITLE
Table report - Turning a URL into a report action creates invalid button

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#553]
When turning a table column into a report action, and that column contains URL strings, the generated buttons show `Object` instead of the actual URL:

![image](https://github.com/neo4j-labs/neodash/assets/1754968/af98a816-f13b-4f23-84a0-1bf6054f0f8e)

Likely this is cause by the new Needle styled links, which are a React object rather than a simple text string or link.

**Comment by alfredorubin96** [comment]
This is fixed, closing this issue.
