### ISSUE TITLE
NeoDash: tab name editing malfunction

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#565]
Editing first tab goes well.
When editing a second, the modification is applied to the first tab, not to the second. See screen movie.

https://github.com/neo4j-labs/neodash/assets/68611501/f1ab4e2d-8ea6-46de-a469-f5444b2f2051

**Comment by gcthys** [comment]
Update:
I just figured out that you have to be on the page of which you want to modify the label. But the "edit" function should only then be available, not when you are still on another page.

**Comment by BennuFire** [comment]
Fixed now on 2.3.3
