### ISSUE TITLE
After setting a dashboard to "editable: false" there is no way back, even as Admin not

### ISSUE THREAD

**Issue by HighlanderJoe** [neo4j-labs/neodash#570]
Hi,

After setting the parameter "editable: false", there is no way back to modify a dashboard anymore. We are currently using Bloom to edit the JSON to turn a dashboard back to editable. Is there not a more convenient way for Admins? 

Kind regards,
Josef

**Comment by BennuFire** [comment]
Fixed now on 2.3.3
