### ISSUE TITLE
Impossible to change report background colour by hex code

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#572]
Impossible to clear any of the hex fields, either by copy/paste, delete or backspace. Field always jumps to some default code. 
RGB fields work fine.
See screen recording:

https://github.com/neo4j-labs/neodash/assets/68611501/e7e2920e-e2ca-4c3c-ab1a-d69783037ce6

**Comment by BennuFire** [comment]
Closed with 2.3.4
