### ISSUE TITLE
Streamline default text colours, please

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#575]
A section of my dashboard look like this:
![image](https://github.com/neo4j-labs/neodash/assets/68611501/88b9382e-fb25-4350-a50d-512b9055b75c)

- dashboard title is black
- tab labels are grey
- report titles are grey
- markup text is black
- parameter search box label is black
- parameter search box content is grey
- table data Including "Query returned no data." are black

This is chaos...
Why was grey introduced in the first place, since it (greatly) reduces legibility?

**Comment by BennuFire** [comment]
Hi @gcthys,

How does it look on http://neodash-test.graphapp.io.s3-website-us-west-1.amazonaws.com/?

**Comment by gcthys** [comment]
Hi @BennuFire ,

can't connect, probably because of the protocol: http://neodash-test.graphapp.io.s3-website-us-west-1.amazonaws.com/ requires Neo4j and my dashboard requires Neo4j+
Guido

**Comment by BennuFire** [comment]
Version 2.3.3 now released should include a better alignment.

However, keep in mind we are currently migrating some components into Needle. That's the reason why some Styles look different from other. This should be fully fixed by the end of this transformation (Giving birth to Neodash 2.4 or 3.0)
