### ISSUE TITLE
Report types can't be switched

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#596]
I often start building a query as a table and once I am sure that all data are being found, I switch to e.g. Graph or Map. 
But since the update I can't switch report types anymore: the pull-down with alternatives doesn't show.

**Comment by BennuFire** [comment]
Hi @gcthys ,

Is it during a Fullscreen report?

**Comment by gcthys** [comment]
Hi @BennuFire, 
Yes, indeed. When in the original format, it switches fine.

**Comment by BennuFire** [comment]
Fixed here https://github.com/neo4j-labs/neodash/pull/626
To be merged

**Comment by BennuFire** [comment]
Fixed on 2.3.5
