### ISSUE TITLE
Adding property to apoc.create.vNode on map throws an error

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#597]
I am showing addresses on a map with the following query:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/c7388157-e1a1-41df-8f73-5c54b9cd29f1)

this works fine:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/07bc25f2-57e2-415c-b01e-9eab9ead6583)

However, when I add an extra property, either FA or FB:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/eb415757-7798-4ff7-9558-9cac184e9493)

the following error appears:

An unexpected error occurred. Try refreshing the component. 

1953/B/u</<@http://neodash.graphapp.io/bundle.js:2:656872
1953/B/u<@http://neodash.graphapp.io/bundle.js:2:656794
1953/B/Y<@http://neodash.graphapp.io/bundle.js:2:655299
B@http://neodash.graphapp.io/bundle.js:2:658069
tl@http://neodash.graphapp.io/bundle.js:152:1681039
Fl@http://neodash.graphapp.io/bundle.js:152:1690557
Hi@http://neodash.graphapp.io/bundle.js:152:1734106
Sc@http://neodash.graphapp.io/bundle.js:152:1720413
_c@http://neodash.graphapp.io/bundle.js:152:1720341
wc@http://neodash.graphapp.io/bundle.js:152:1720202
hc@http://neodash.graphapp.io/bundle.js:152:1717189
57799/Wo/<@http://neodash.graphapp.io/bundle.js:152:1666961
41196/n.unstable_runWithPriority@http://neodash.graphapp.io/bundle.js:152:1837862
Ho@http://neodash.graphapp.io/bundle.js:152:1666738
Wo@http://neodash.graphapp.io/bundle.js:152:1666908
Vo@http://neodash.graphapp.io/bundle.js:152:1666841
Mc@http://neodash.graphapp.io/bundle.js:152:1726289
41196/n.unstable_runWithPriority@http://neodash.graphapp.io/bundle.js:152:1837862
Ho@http://neodash.graphapp.io/bundle.js:152:1666738
Pc@http://neodash.graphapp.io/bundle.js:152:1725566
57799/Rc/<@http://neodash.graphapp.io/bundle.js:152:1725477
D@http://neodash.graphapp.io/bundle.js:152:1836923
41196/y.port1.onmessage@http://neodash.graphapp.io/bundle.js:152:1835646

**Comment by BennuFire** [comment]
Hi @gcthys , 

Does this still happens? If so, can you run the second query on the browser and share the first 2 results?

Thanks

**Comment by gcthys** [comment]
Hi, @BennuFire,

no, for some reason it works now, although I didn't change anything.
So, please mark as resolved.
Thanks.
Guido
