### ISSUE TITLE
ARM64 docker image

### ISSUE THREAD

**Issue by diyoyo** [neo4j-labs/neodash#609]
## Guidelines
Please note that GitHub issues are only meant for bug reports/feature requests.

## Feature request template

**Is your feature request related to a problem? Please describe.**
I can't install NeoDash's docker image on my RaspberryPi running Raspbian (ie Debian)

**Describe the solution you'd like**
A nice person compiling the image for arm64 and loading it on hub.docker.com

**Describe alternatives you've considered**
Compiling it myself, but I don't have the skills yet.

**Additional context**
Pleaaase 🥺

**Comment by diyoyo** [comment]
Ok, I guess it was not so complicated, I hadn't seen the instructions available here: 
 https://neo4j.com/labs/neodash/2.2/developer-guide/build-and-run/

My 2-cent suggestion would be, in the "Docker" paragraph, to re-add the line:
`clone the repository` as the very first step to perform before `docker build . -t neodash`

Also, there is a dash "-" missing in the last command: it should be `docker run -it –-rm -p 5005:5005 neodash` instead of `docker run -it –rm -p 5005:5005 neodash
`

Finally, before being able to share my build with the community, I still need to figure out how to provide credentials when neo-dash and the neo4j server are not running on the same machine...

**Comment by diyoyo** [comment]
Ok, sorry again If I solved my own problem. The configuration was just one step away.
I guess I could not see it because at first, I had only two options:
- Create new Dashboard
- Try a Demo.

So I had to create a new Dashboard to establish the first connection, and then only I was able to load the existing dashboards saved directly in the neo4j database.

**Comment by BennuFire** [comment]
Hi @diyoyo!

Thanks for the 2 cents. I'll keep it on mind!
