### ISSUE TITLE
table widget filter hiding first value

### ISSUE THREAD

**Issue by v2belleville** [neo4j-labs/neodash#629]
this is a UI issue: if you filter a table, the first value is hidden by the prompt pop up. In the first screenprint type "Personne" is not visible when filtered

![image](https://github.com/neo4j-labs/neodash/assets/8779004/4cf6aedf-b977-43a4-a3ca-a43624dc24bf)

![image](https://github.com/neo4j-labs/neodash/assets/8779004/ec72fe9c-a400-4f1f-baeb-fdda2f5ea8ad)

**Comment by JonanOribe** [comment]
@v2belleville, do you prefer the filter on this position? 
![image](https://github.com/neo4j-labs/neodash/assets/11914201/f0740921-f97c-4461-95a2-fa9826083225)

**Comment by alfredorubin96** [comment]
Closing because it has been fixed with #712

**Comment by v2belleville** [comment]
sorry I missed your question @JonanOribe . good to see it's apparently fixed. 

Haven't used Neodash in a while, will definitely check it out !

**Comment by JonanOribe** [comment]
> sorry I missed your question @JonanOribe . good to see it's apparently fixed.
> 
> Haven't used Neodash in a while, will definitely check it out !

Ya, don't worry.Anything you need, just tell me
