### ISSUE TITLE
Parameter Selector Doesn't refresh when a report action sets a parameter

### ISSUE THREAD

**Issue by GQ16** [neo4j-labs/neodash#653]
- NeoDash version: 2.3.5
- Neo4j Database version: 4 Aura DB

- **Steps to reproduce**
- Expected Behavior: When I use a report action to set a parameter for other visuals, such as clicking a cell in a table, I expect it to refresh the dependent visuals and also automatically refresh/populate the parameter selector I have that shares/sets the same parameter id ($neodash_location_id_1).
- Actual behavior: The report action does refresh/set the dependent visuals (AKA other charts) but it doesn't refresh the parameter selector. The corresponding parameter selector just stays blank until I click the three dots (edit button) and then run the parameter selector widget again (the play/run button) which finally refreshes it to show the value I had selected from my report action. But every time I use the report action I have to go edit and rerun the parameter selector to see the value.

Screenshots and drawings to replicate the issue:
![image](https://github.com/neo4j-labs/neodash/assets/107271596/9773fa9a-b990-4584-b195-29150ad86fbe)
![image](https://github.com/neo4j-labs/neodash/assets/107271596/b84f9439-50c6-4568-a58e-e31135858cf2)
![image](https://github.com/neo4j-labs/neodash/assets/107271596/1f909d99-d776-443a-8832-b2b543557b03)
![image](https://github.com/neo4j-labs/neodash/assets/107271596/8624b957-8b49-492e-adb2-36c156d3803b)

**Comment by m-o-n-i-s-h** [comment]
Hi @GQ16 , Are you looking for something like this ?
![parameterupdate](https://github.com/neo4j-labs/neodash/assets/139316519/04782108-656a-4299-b82f-da3ef59ffaba)

**Comment by GQ16** [comment]
@m-o-n-i-s-h 
Yes but here is what is happening:
![2023-10-11_11-53-28](https://github.com/neo4j-labs/neodash/assets/107271596/19f9fcd3-1122-449d-812d-5c5f841e3b33)
