### ISSUE TITLE
Report action for link parameters sets invalid state object

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#659]
To reproduce:
1. Create a table that returns a url `http://example.com`.
2. Create a report action that sets a parameter `$neodash_url` to this value.
3. Create an iFrame that uses `$neodash_url` as input. This will not work as the data type is not a string, but a link object.

**Comment by diyoyo** [comment]
Same bug here.

Troubleshooting so far:
- tested the parameter in a `Single Value` card , using `return $neodash_url` → URL appears correctly, and is clickable (event target=_blank)
- tested the parameter in the title of the card → `[Object object]`
- tested the parameter in the iFrame, but with `return $neodash_url`→ Not working
- Played with the toggles of the Advanced Parameters →  Not working
- Tested back on v2.3.4 → Working fine again

Conclusion : **this bug appeared in v2.3.5.**

Server: Linux Debian 12
Docker: v 24.0.6
NeoDash version: 2.3.5 - arm64
Neo4j: v5.11.0 ce
Browser: Brave (all shields down) for macOS

**Comment by diyoyo** [comment]
Bug still present in 2.4.1 (arm64 self-build)

**Comment by diyoyo** [comment]
@nielsdejong am I the only one having this issue?

**Comment by thegallier** [comment]
No.  Similar issue with multi select.  Getting [object Object] in titles.  Looks good in queries.

**Comment by nielsdejong** [comment]
Fixed in https://github.com/neo4j-labs/neodash/pull/744, to be released as part of 2.4.2!
