### ISSUE TITLE
Table report - hide action buttons for empty strings

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#660]
![image](https://github.com/neo4j-labs/neodash/assets/1754968/c78050d3-92fa-4ce6-86f7-10d028167c21)
^ to avoid this behaviour with incorrectly formatted buttons.

**Comment by alfredorubin96** [comment]
We should also work on fixing the size of the text inside the button, in some cases it overflows, making impossible to read the field's content

**Comment by nielsdejong** [comment]
Fixed in https://github.com/neo4j-labs/neodash/pull/744.
