### ISSUE TITLE
Text hard to read on Dark Theme

### ISSUE THREAD

**Issue by JonanOribe** [neo4j-labs/neodash#667]
NeoDash version: 2.3.4

Neo4j Database version: 5.11.0 Community.

Steps to reproduce

Switch to dark mode

Try to read de footer

Actual behavior: text over colored labels is imposible to read

![image](https://github.com/neo4j-labs/neodash/assets/11914201/633e0525-5c63-4775-a4d1-49f5afb652e3)

Expected behavior: text should be readable

![image](https://github.com/neo4j-labs/neodash/assets/11914201/9730fdbe-d21a-4f4b-a85b-5715f396c8ca)

**Comment by nielsdejong** [comment]
Resolved in 2.4.0
