### ISSUE TITLE
Parameter select autocompletion doesn't show a property linked to the given Label

### ISSUE THREAD

**Issue by mgazanayi** [neo4j-labs/neodash#686]
## Description:

When creating a parameter select, there is a problem when trying to find the property of a given Label.

- The proposed properties are not those of the given label (it proposes every property since based on `db.propertyKeys()` which doesn't link the properties to the given Label
- If your database contains a lot of properties containing the word you are looking for (in my case id) it's probable that your property will not be shown among the 5 proposed fields (I have to download the file and modify it manually, then import it back).

## Tested version:

- NeoDash version: 2.3.5
- Neo4j Database version: 4.4.19 (Enterprise).

## Steps to reproduce:

- When selecting a Label, I want to see the autocomplete only on the properties of that label
- When selecting a Label, I can see autocomplete on other properties containing the property I'm looking for, even not linked to the selected Label, and also, it is not shown since only proposing 5 properties.

**Comment by alfredorubin96** [comment]
Has this been completed? if not, there is a PR for this issue?
