### ISSUE TITLE
Map: two points at same location

### ISSUE THREAD

**Issue by JoridK** [neo4j-labs/neodash#69]
Hi,

I've been playing around a bit with NeoDash, and most features are very easy to use :)

One minor bug I found is in the map, if I have two nodes at the same location. In that case, only one of them is displayed, and the other just vanishes.

**Comment by nielsdejong** [comment]
hi @JoridK ,
Just tried this as well and it seems to the same for me. How'd you suggest fixing this?
I'm having trouble coming up with a nice solution so that both are visible at the same time, any ideas?

**Comment by JoridK** [comment]
The best I can think of is to put one point in a slightly wrong place next to the other, if two points have the same location (if there are more than two points, the third point would need to be offset in a slightly different direction, etc) . I think on most maps it will not matter whether it is offset by a couple of centimeters in comparision to real life. 
In case it is critical for some use case, maybe you could make this feature optional?

**Comment by nielsdejong** [comment]
Hi @JoridK ,

I thought a bit about your comment and came up with another idea. What about having a small number below the marker that appears when there's >1 point at this location. The inspect view after clicking will then show details on both nodes. I think this is also how other map libraries do it. What do you think?

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1754968/154217250-e585d67f-b34f-4c9a-a955-4aa48f4f380b.png">

**Comment by BennuFire** [comment]
Closed in 2.3
