### ISSUE TITLE
Load dashboard from share link - Wrong database

### ISSUE THREAD

**Issue by mariusconjeaud** [neo4j-labs/neodash#704]
- NeoDash version : 2.4.0

On a server with multiple databases, I generated a share link for a dashboard saved in the database named `citation`. The link is like so : http://neodash.graphapp.io/?share&type=database&id=c20b96af-db53-45fd-9f10-fb0de14274ae&dashboardDatabase=citation

But when clicking on the link, after connection page, I get the following error message :
![image](https://github.com/neo4j-labs/neodash/assets/7679761/24aa157d-4560-45dc-af6d-72de76abc9dd)

Note : I am properly logged in to Neo4j because I see the right list of available databases in the dashboard list sidebar, and all my saved dashboards

**Comment by alfredorubin96** [comment]
Found the bug, there was a problem with the refresh of the dashboard list. Hopefully we will get out with the new release

**Comment by nielsdejong** [comment]
Fixed in https://github.com/neo4j-labs/neodash/pull/744 - database was not set correctly as part of sharing logic.
