### ISSUE TITLE
When loading a dashboard from the DashboardSidebar, first loading uses uncasted parameters

### ISSUE THREAD

**Issue by alfredorubin96** [neo4j-labs/neodash#717]
^read title 

- NeoDash version: 2.4.0
- Neo4j Database version: Any

- **Steps to reproduce**

1.    Load a dashboard that contains a param that should be a date (loading in the first connection works)
2.    Select another dashboard
3.    Select the first dashboard

- Expected behavior

Should show the same result as loading at the first connection

- Actual behavior
The first query of every card in the first rendered page is running using uncasted parameters, while any subsequent query will use the correct parameters.

**Comment by nielsdejong** [comment]
Fixed in https://github.com/neo4j-labs/neodash/pull/727
