### ISSUE TITLE
Error message while saving dashboard in v2.4.0.

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#718]
Using the left sidebar, when I save the current draft to neodashgraphs, the following error message appears:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/626e6067-3c45-4eb3-8b95-85f4c08a1e17)

**Comment by alfredorubin96** [comment]
Thank you for reporting this bug, can you please provide the dashboard export?

**Comment by alfredorubin96** [comment]
Can you please check it for 2.4.1 ?

**Comment by gcthys** [comment]
Solved, thank you.
