### ISSUE TITLE
New left sidebar incomplete in Firefox

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#719]
The symbols that appear in Opera and Chrome:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/e7903ffc-d86b-418d-8962-e4b8d027b880)

are not visible in Firefox:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/29cab466-2189-4407-ada1-e1ab7346af56)

**Comment by alfredorubin96** [comment]
Thank you for reporting this bug. I'm trying to replicate the bug but I can't replicate it. Can you please provide the version of Firefox so that we can replicate it?

**Comment by gcthys** [comment]
Sorry, missed your reaction.

Seems to be uptodate: 121.0 (64-bits)

Checked again today and symbols are still missing

**Comment by nielsdejong** [comment]
Hi @gcthys , I was able to replicate this bug and have pushed a fix as part of https://github.com/neo4j-labs/neodash/pull/744.
The fix will be out to https://neodash.graphapp.io as part of the 2.4.2 release. 
Thanks for letting us know!
Niels
