### ISSUE TITLE
iFrame not reading global parameters, throwing error instead

### ISSUE THREAD

**Issue by jacobbleakley-neo4j** [neo4j-labs/neodash#740]
- NeoDash version: 2.4.1 (tried locally and on neodash.graphapp.io)
- Neo4j Database version: 5.3.0 Enterprise

- Steps to reproduce: 1. Create a table that returns a link, create report action to set link to a global parameter. 2. Return global parameter in iFrame query.
- Expected behavior: iFrame report card has url destination embedded.
- Actual behavior: Error message "Invalid iFrame URL. Make sure your url starts with http:// or https://."

**Comment by nielsdejong** [comment]
Solved this one as part of the fix for https://github.com/neo4j-labs/neodash/issues/659.
Part of https://github.com/neo4j-labs/neodash/pull/744 - to be released with 2.4.2.
