### ISSUE TITLE
Bar chart hover gone after update from 2.4.0 to 2.4.1

### ISSUE THREAD

**Issue by ivy113** [neo4j-labs/neodash#750]
Using docker images, I am noticing that I can hover and see values for Bar Charts on 2.4.0 but not 2.4.1. 

- NeoDash version: 2.4.1

**Comment by nielsdejong** [comment]
hi @ivy113 ,
Thanks for reporting this issue. It looks like our switch to a custom bar component has disabled the tooltip.
We'll probably need to come up with a solution like this one:
https://codesandbox.io/p/sandbox/bold-jennings-1d6y3?file=%2Fsrc%2FApp.tsx%3A30%2C21-30%2C62

We will keep you posted on the progress.
CC @jacobbleakley-neo4j @alfredorubin96

**Comment by jacobbleakley-neo4j** [comment]
Please @alfredorubin96 would you be able to see if you can implement the bar chart hover on the custom 'BarComponent'? I'm happy to look at this with you if needs be.

**Comment by nielsdejong** [comment]
Fixed by #760
