### ISSUE TITLE
3D Graph doesn't show

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#759]
The query:

`MATCH (p:Producer)-[r:HAS_NAME_VARIANT]->(n:Name)
WHERE n.NameID = $neodash_name_nameid
MATCH (p)-[r3:HAS_NAME_VARIANT]->(n2:Name)
OPTIONAL MATCH (n2:Name)-[r4:NAME_FOUND_IN]->(s2:Source)
OPTIONAL MATCH (s2:Source)-[a:APPEARED_IN]->(s3:Source)
OPTIONAL MATCH (n2:Name)-[v:VERBAL_SOURCE]->(p2:Producer)-[r6:HAS_NAME_VARIANT {qualification :"preferred"}]->(n3:Name)
RETURN *`

produces the following 2D Graph:
![Schermafbeelding 2024-01-17 151123](https://github.com/neo4j-labs/neodash/assets/68611501/4620945b-e6e0-4382-a2bd-42a32ffa5423)

but the 3D Graph report is empty:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/126652a0-924d-4b36-831a-ecf20026deee)

(Advanced Visualisations extension is on)

**Comment by nielsdejong** [comment]
hi @gcthys ,
Can you send me the value for $neodash_name_id?
I tried with your database but it seems to work on my side. I'm trying with `N2503`:

<img width="1327" alt="image" src="https://github.com/neo4j-labs/neodash/assets/1754968/9808d47b-38c2-4e2a-9b38-684d7dc24002">

**Comment by gcthys** [comment]
I tried with different values but none of them worked.
See screen recording:

https://github.com/neo4j-labs/neodash/assets/68611501/dcc991cb-0a89-4939-9122-005c1ea4c326

**Comment by nielsdejong** [comment]
Hi Guido,

I discovered the problem.
Looks like your background color is not a valid string, namely `#D1FFC9.     ` instead of just `#D1FFC9`.
You can make it work again by removing the spaces at the end.


It seems that the 3D graph library is less robust than the 2D one. I'll create a fix for this soon.

Thanks for discovering this one,
Niels

**Comment by gcthys** [comment]
You're welcome!
