### ISSUE TITLE
Text2Cypher Plugin: Query Examples not removable due to clipping off-screen

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#766]
![Screenshot 2024-01-25 at 09 37 50](https://github.com/neo4j-labs/neodash/assets/1754968/1f47ce8c-dacf-47d3-9812-746d1a4ab264)

**Comment by jacobbleakley-neo4j** [comment]
Pull request created. Awaiting review

**Comment by nielsdejong** [comment]
Resolved by https://github.com/neo4j-labs/neodash/pull/768
