### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by ivy113** [neo4j-labs/neodash#771]
I usually run a Docker image for the standalone neodash. When I edit a development dashboard then push a change, a user with a standalone dashboard link already open does not always see the change I made. (If they have never opened the link before, this does not appear to be an issue.) The fix I have used is a hard refresh via CTRL + SHIFT + R but it is tricky to convince end users they need to do this to make sure the version and link is up to date.

- NeoDash version: 2.4.2

**Comment by nielsdejong** [comment]
Fixed by #788
