### ISSUE TITLE
GraphChart report action - Not Working

### ISSUE THREAD

**Issue by alfredorubin96** [neo4j-labs/neodash#778]
The Report action stopped working for the graph
- NeoDash version: 2.4.2
- Neo4j Database version:Any

- **Steps to reproduce**
- Create a report action to click a node in the GraphChart and sets the parameter during the click event
- Actual behavior
- Doesn't Work

**Comment by sirko-schroeder** [comment]
This is a bit of a show stopper here too. Is there a workaround for this issue yet?

**Comment by alfredorubin96** [comment]
Currently working on it, we will keep you posted.

**Comment by nielsdejong** [comment]
Resolved by #782
