### ISSUE TITLE
Question: Is it possible to present clickable links in table reports?

### ISSUE THREAD

**Issue by m-crown** [neo4j-labs/neodash#780]
Many times I want to be able to display a hyperlink in an output table report, allowing users to breakout to another site. I have tried restlying an output in HTML format, and also in markdown format, but neither formats into a link, and just shows the raw output. Is it possible to present clickable links in tables?

Additionally, I find when using neodash in neo4j desktop, I am unable to click through on any links, but when in the browser links clickthrough properly. Is there some config option I can set to enable this functionality in desktop? 

Thanks, 

Matt

**Comment by alfredorubin96** [comment]
Thank you for submitting this issue, can you please give us some example data? From our side the Table chart can render hyperlinks and they are clickable.

**Comment by m-crown** [comment]
Thanks for getting back to me.

I was trying to format in markdown an output - but I realise now that the links work if formatted as plain text. 

Thanks!
