### ISSUE TITLE
Parameter Select issue with mouse movement

### ISSUE THREAD

**Issue by geoffinfosecpersona** [neo4j-labs/neodash#792]
To help us understand your issue, please specify important details, primarily:

- NeoDash version: 2.4.2
- Neo4j Database version: 5.12 (Enterprise)

- **Steps to reproduce**
We have a Parameter Select report that sets a property given a specific node label, and the property *which is an integer* (not sure if that's the key to the issue or not)

This works as expected so long as we're really careful about changing the integer after one has already been entered.  

If we're a little sloppy with the mouse though and highlight the numbers (possibly making the UI think we're moving the numbers), the Report fails with the error:

An unexpected error occurred. Try refreshing the component. 

```
TypeError: s.toLowerCase is not a function
    at https://your.url.here/bundle.js:2:9596913
    at v (https://your.url.here/bundle.js:2:9598851)
    at https://your.url.here/bundle.js:2:9619699
    at ti (https://your.url.here/bundle.js:152:1553619)
    at Ni (https://your.url.here/bundle.js:152:1561763)
    at Hl (https://your.url.here/bundle.js:152:1607754)
    at Ec (https://your.url.here/bundle.js:152:1592991)
    at _c (https://your.url.here/bundle.js:152:1592919)
    at wc (https://your.url.here/bundle.js:152:1592782)
    at hc (https://your.url.here/bundle.js:152:1589769)
```

This requires logging out and back in to the dashboard to make the Parameter Select report usable again.

**Comment by alfredorubin96** [comment]
Thank you for your feedback, it will be out in the next release.

**Comment by alfredorubin96** [comment]
Could you check that it works now?

**Comment by geoffinfosecpersona** [comment]
Alfredo,

Apologies for the delay in getting back, what version is this fixed in?  We're still on 2.4.3 because of SSO auth issues with 2.4.4.

Thanks!

**Comment by alfredorubin96** [comment]
It should've been fixed in 2.4.4, could you please check? If you get the same bug, please share a screen share and the dashboard json if possible.

**Comment by geoffinfosecpersona** [comment]
Alfredo,

Apologies, we can't check, as we're still on 2.4.3 because of SSO auth issues with 2.4.4.

**Comment by geoffinfosecpersona** [comment]
Alfredo, just moved to 2.4.4 and can validate that this bug has been squashed.  Thank you!
