### ISSUE TITLE
Ability to hard hide extra columns in tables used for report actions

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-labs/neodash#812]
## Guidelines
Please note that GitHub issues are only meant for bug reports/feature requests.

## Feature request template

**Is your feature request related to a problem? Please describe.**
Yes I want to use report actions as a type of selector to populate parameters.  I want to - in edit mode - to hide all other columns other than the "click" column.

**Describe the solution you'd like**
In edit mode, select a table column for hiding. 
Have it stay hidden on refresh when not in edit mode.

**Describe alternatives you've considered**
I tried setting the column widths in the table to proportional [0] and also 0 px.  
Columns are still visible.

**Additional context**
here is a screenshot showing all the extra columns.
I'm using the table as a report action selection mech - because I can populate a bunch of params at once.
These params are mapped to  markdown text for display in the markdown component.

Thank you! 
-Michael

current

<img width="630" alt="image" src="https://github.com/neo4j-labs/neodash/assets/5991751/d91e7205-46b3-4716-83d0-e8c527ab6718">

desired

<img width="630" alt="image" src="https://github.com/neo4j-labs/neodash/assets/5991751/abbe626b-3a28-4590-9116-a083119af90e">

**Comment by m-crown** [comment]
You can do this by prefixing alias of the columns to be hidden with double underscore

**Comment by alfredorubin96** [comment]
Dear @graphadvantage, thank you for pushing this issue. To hide a column, you can add the prefix __ (double underscore) to the names of the columns you want to hide. I will then close this issue because not needed
