### ISSUE TITLE
[Feature Request] Add ability to fill vertical white space with tiles

### ISSUE THREAD

**Issue by emigre459** [neo4j-labs/neodash#82]
As different tile types often need to have a larger footprint to be useful outside of fullscreen view (e.g. Graph tiles), but others don't need such a large footprint (e.g. Parameter Select tiles), there are often cases like the one in the attached image in which I end up with a good amount of vertical white space. Since we can only move tiles left and right within a dashboard right now, there's no way to take a short tile and place it beneath another short tile, if they're in the same row as a tall tile.

The most straightforward solution would be drag-and-drop tile placement, but I know that's difficult for this tech stack. So perhaps an up/down arrow to complement the left/right arrow functionality?

![image](https://user-images.githubusercontent.com/11720378/154324246-8b7af022-0eb6-4e3a-a9e9-c5938f765398.png)

**Comment by nielsdejong** [comment]
Hi @emigre459 ,

Thanks for the suggestion. This is unfortunately an artifact of how react-material deals with grid layouts so there's not too much I can do about it at this point.

On the other hand - I've been doing some investigating into a resizable grid layout and it is looking awesome:
https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html

issue there is that I'll have to change a bunch of things, including the format in which dashboards are stored. I'll probably put in in the 2.1 release for this reason. What do you think?

**Comment by emigre459** [comment]
I just played around with the `react-grid-layout` you linked to and it seems to solve all the problems! I'm sure a lot would be needed to make sure errors don't pop up/text floats off into space/etc. in the tile contents as a result, but this would definitely solve the problem.

From an engineering perspective, totally understand the need to wait to put it into a minor version instead of a patch version. Do you have an estimate as to when you expect the next minor version to be put out?

**Comment by BennuFire** [comment]
Good news @emigre459 ! It's coming soon ⏲️

**Comment by BennuFire** [comment]
Closed on 35291192802ada6cf75d433113632ad1a42cd573
Version 2.1.1

Enjoy!
