### ISSUE TITLE
[Feature Request] Table Column Dynamics

### ISSUE THREAD

**Issue by emigre459** [neo4j-labs/neodash#84]
Right now, there are two problems I keep running into with Table-type tiles:

1. Column size adjustments are awkward. Using the advanced setting that allows for relative column widths gets the job done, but requires a bunch of iterations usually before you get it right. Making this a dynamic/drag-and-drop functionality would be the ideal.
2. Related, and possibly making the first item slightly lower priority if implemented, is automatically word-wrapping in table cells, especially the column headers. All too often I have to increase column width only because my column header is too long to fit in the header cell (and I can't reduce the character count any further without losing info for my users). If these were to automatically (and/or optionally) word wrap, that would be amazing. Pushing the bottom few rows to a new page of the table is fine usually when it means you can see the whole header easily.

**Comment by emigre459** [comment]
1. Sad to hear that you would need the pro license to accomplish this (and thus it's not an option for an open source project). At the risk of suggesting something you have thoroughly investigated and found insufficient already, what about something else that (seems to be) pure open source for tables, like [React-Table](https://react-table.tanstack.com/)? I freely admit I don't know what it means when it says it's "only hooks" so it may be a bad fit, not sure.
2. I'd prefer the option to word-wrap vs. truncate and provide the full name on hover as an advanced setting, if possible (with truncation as the default probably). I have users that will likely just ignore the whole column if they have to put any work into figuring out what it is (even hovering).

**Comment by JoridK** [comment]
Agree with both points in this request. Especially point 1 would be great to have, especially when deploying a dashboard in standalone mode, so that viewers can adjust the columns as necessary for their screen / data.

**Comment by KWLangendorf** [comment]
Hi, word-wrap in tables would be nice - or perhaps support for \n as in https://github.com/neo4j-labs/neodash/issues/310 then you can make a query to add a newline if beyond a certain limit.
Table with need for word-wrapping (study_title) - the \n is not supported in the table:
<img width="1155" alt="image" src="https://github.com/neo4j-labs/neodash/assets/26305820/e8269826-3028-48b5-a8c6-2e1a22a0fd21">
Here the same query in browser (inserting \n if beyond 60-65 characters)
<img width="1138" alt="image" src="https://github.com/neo4j-labs/neodash/assets/26305820/fb735382-661d-4f43-843a-4321e54a3885">

**Comment by KWLangendorf** [comment]
@nielsdejong added screenshot of the wrap_limit 
![image](https://github.com/neo4j-labs/neodash/assets/26305820/74bc265e-3efe-4aae-be3a-17affa11689c)
