### ISSUE TITLE
loggingDatabase default is not documented correctly

### ISSUE THREAD

**Issue by blongv** [neo4j-labs/neodash#915]
## Guidelines
Please note that GitHub issues are only meant for bug reports/feature requests. 

Before creating a new issue, please check whether someone else has raised the same issue. You may be able to add context to that issue instead of duplicating the report. However, each issue should also only be focussed on a _single_ problem, so do not describe new problems within an existing thread - these are very hard to track and manage, and your problem may be ignored. Finally, do not append comments to closed issues; if the same problem re-occurs, open a new issue, and include a link to the old one.

To help us understand your issue, please specify important details, primarily:

- NeoDash version: 2.4.8
- Neo4j Database version: 5.14.0-enterprise

- **Steps to reproduce**
Based on [config-entrypoint.sh](https://github.com/neo4j-labs/neodash/blob/42b196a3ec9a1d5740e4c81420a762646b1295b7/scripts/config-entrypoint.sh#L26), the default loggingDatabase is `logs` not `neo4j` as stated in the [documentation](https://neo4j.com/labs/neodash/2.4/developer-guide/configuration/#_configuration_options).

**Comment by AleSim94** [comment]
Thank you so much for this observation @blongv! we will try to fix this very soon :)
