### ISSUE TITLE
[Feature Request] Adding time ranges

### ISSUE THREAD

**Issue by andyagtech** [neo4j-labs/neodash#96]
I am looking for options to visualize [temporal](https://neo4j.com/docs/cypher-manual/current/syntax/temporal/) graph data. Many of our nodes and edges have time data on them, and it would be very helpful to be able to visualize how these change over time. So I am thinking of a graph view with some sort of time range.

As far as interfaces go, I can think of two main modes :
- Before or after a specific time
- Between two times

(Thank you for the very wonderful tool!)

**Comment by nielsdejong** [comment]
Hi @elandybarr, thanks for your suggestion.
Perhaps you could make a quick sketch of your intended UI and post it here? I'm struggling to come up with how exactly to visualize this.

Do you imagine it similar to this: https://linkurious.com/blog/time-filtering-linkurious/ ?

Thank you.
Niels

**Comment by elandybarr** [comment]
![image](https://user-images.githubusercontent.com/3634832/158804817-0130cbbb-62c6-4ff4-a17c-f6fae5343589.png)

Here is something along the lines of what I was thinking. I think we would need a way to choose a field (maybe there is a 'created_at', 'updated_at', etc for a given relation) and then a way to constrain them (I'm not sure what is the best selector for a datetime).

**Comment by alfredorubin96** [comment]
Hi @andyagtech , i think you can achieve the same if you use the new Form report with two date pickers (one for the start and one for the end)

**Comment by alfredorubin96** [comment]
I will close this issue because the answer has been given more than a month ago. Feel free to reopen it if you think you need further information
